export const APP_VERSION = '1.7.59'
export const APP_VERSION_DATE = '2026-05-14'
export const APP_VERSION_TIME = '22:53'

export const RELEASE_NOTES = [
  {
    version: '1.7.59',
    date: '2026-05-14',
    time: '22:53',
    title: 'Página de sugestões visível na área de administração',
    changes: ['Administradores podem consultar todas as sugestões enviadas em "Administração → Sugestões"'],
  },
  {
    version: '1.7.58',
    date: '2026-05-14',
    time: '22:48',
    title: 'Resposta "Resolvido ✓" fecha o ticket automaticamente',
    changes: [
      'Quando um técnico ou administrador usa o botão "Resolvido ✓" para responder, o ticket é automaticamente fechado ao enviar.',
      'O botão fica verde quando selecionado para indicar que o ticket será fechado com o envio.',
      'Todos os tickets que já estavam em estado "Resolvido" foram automaticamente fechados no arranque.',
    ],
  },
  {
    version: '1.7.57',
    date: '2026-05-14',
    time: '13:14',
    title: 'Direitos de autor e propriedade intelectual',
    changes: [
      'Adicionada secção "Direitos de autor" na página Sobre com a declaração de propriedade exclusiva e proibição de utilização não autorizada.',
      'Criado ficheiro LICENSE no repositório GitHub com aviso completo em português e inglês.',
    ],
  },
  {
    version: '1.7.56',
    date: '2026-05-14',
    time: '11:27',
    title: 'Badge "F" laranja para tickets escalados ao fornecedor',
    changes: [
      'Nas listas de tickets, os tickets escalados para o fornecedor externo passam a mostrar um círculo laranja "F" ao lado do estado.',
      'O indicador é visível tanto em "Os meus tickets" como em "Gestão de tickets".',
    ],
  },
  {
    version: '1.7.53',
    date: '2026-05-14',
    time: '11:09',
    title: 'Indicador "Fornecedor" nas listas de tickets',
    changes: [
      'Nas listas "Os meus tickets" e "Gestão de tickets", os tickets escalados para o fornecedor externo passam a mostrar uma etiqueta laranja "Fornecedor" ao lado do estado.',
      'A etiqueta desaparece automaticamente quando o técnico regista que o fornecedor resolveu o problema.',
    ],
  },
  {
    version: '1.7.52',
    date: '2026-05-14',
    time: '09:26',
    title: 'Estados e prioridades traduzidos nos emails',
    changes: [
      'Os emails de atualização de ticket passam a mostrar o estado e a prioridade em português: Aberto, Em Curso, A aguardar utilizador, Resolvido, Fechado; Baixa, Média, Alta, Urgente.',
    ],
  },
  {
    version: '1.7.51',
    date: '2026-05-14',
    time: '09:11',
    title: 'Destinatários de sugestões configuráveis',
    changes: [
      'Nas Configurações → Notificações, o administrador pode agora definir os emails que recebem uma notificação quando é enviada uma nova sugestão.',
      'O email de notificação inclui o nome do autor, a data e o texto da sugestão.',
    ],
  },
  {
    version: '1.7.50',
    date: '2026-05-14',
    time: '09:02',
    title: 'Sugestões, traduções e limpeza de atualizações',
    changes: [
      'Novo menu "Sugestões" no painel lateral — qualquer utilizador autenticado pode enviar ideias ou sugestões de melhoria da aplicação.',
      'Os eventos dos tickets passam a mostrar os estados e prioridades em português: Aberto, Atribuído, Em Curso, A aguardar utilizador, Resolvido, Fechado; Baixa, Média, Alta, Urgente.',
      'Histórico de atualizações: removidas entradas sobre notificações push que não estavam a funcionar de forma fiável.',
    ],
  },
  {
    version: '1.7.49',
    date: '2026-05-13',
    time: '09:47',
    title: 'Emails silenciados',
    changes: [
      'Corrigido um problema onde autores que desativavam "Atualizações por e-mail" continuavam a recebê-las se pertencessem a uma equipa ou grupo designado para resolver esse pedido.',
    ],
  },
  {
    version: '1.7.48',
    date: '2026-05-13',
    time: '09:35',
    title: 'Usabilidade móvel',
    changes: [
      'A barra de navegação (separadores) no telemóvel permite agora deslizar suavemente com o dedo de forma muito fluida, e as barras de scroll foram escondidas para um aspeto mais limpo.',
    ],
  },
  {
    version: '1.7.47',
    date: '2026-05-13',
    time: '09:28',
    title: 'Menus de navegação mais modernos',
    changes: [
      'O design dos menus de navegação (separadores) nas Configurações e nos Utilizadores foi totalmente modernizado.',
      'Os separadores funcionam agora num formato "pílula" (segmented control) com melhor contraste, legibilidade e aspeto premium, tanto em modo claro como escuro.',
    ],
  },
  {
    version: '1.7.46',
    date: '2026-05-13',
    time: '09:23',
    title: 'Lista de membros de grupos mais limpa',
    changes: [
      'A gestão de grupos passou a apresentar apenas os membros atuais do grupo por defeito.',
      'Os restantes utilizadores só aparecem se utilizar a caixa de pesquisa, tornando a gestão de equipas muito mais simples sem uma lista interminável de utilizadores.',
    ],
  },
  {
    version: '1.7.45',
    date: '2026-05-13',
    time: '09:18',
    title: 'Cor da nota interna no modo escuro',
    changes: [
      'Corrigida a legibilidade do texto das notas internas quando o modo escuro está ativo, alterando a cor de fundo para uma tonalidade adequada.',
    ],
  },
  {
    version: '1.7.44',
    date: '2026-05-12',
    time: '19:43',
    title: 'Atribuição por técnicos e emails mais completos',
    changes: [
      'O campo "Atribuído a" passa a abrir imediatamente a lista de técnicos ativos disponíveis, sem obrigar a saber ou escrever o nome.',
      'Um utilizador pode manter o papel de Administrador e ser marcado também como técnico para poder receber tickets.',
      'Tickets só podem ser atribuídos a técnicos ativos ou utilizadores marcados como técnicos, evitando atribuições diretas a administradores puros.',
      'Utilizadores locais podem ser criados com emails externos ao domínio @queiroz.pt.',
      'Os emails de criação de ticket passam a incluir o conteúdo do pedido enviado pelo utilizador.',
      'SLA foi renomeado para Tempo de resposta, com 48h por defeito e ajuste para o próximo dia útil quando o prazo cai ao fim de semana.',
    ],
  },
  {
    version: '1.7.43',
    date: '2026-05-12',
    time: '18:23',
    title: 'Pesquisa móvel em conhecimento e vários técnicos por ticket',
    changes: [
      'Corrigido o campo "Em conhecimento" no detalhe do ticket em dispositivos móveis: deixa de carregar uma lista gigante e passa a mostrar apenas resultados filtrados por nome, email ou utilizador.',
      'Tickets criados por regras de encaminhamento passam a guardar também o técnico da categoria na nova lista de responsáveis.',
      'O detalhe do ticket permite agora atribuir vários técnicos ativos ao mesmo pedido, removendo ou acrescentando responsáveis sem recriar o ticket.',
      'As notificações por email passam a considerar todos os técnicos atribuídos, não apenas o primeiro responsável.',
    ],
  },
  {
    version: '1.7.42',
    date: '2026-05-11',
    time: '15:38',
    title: 'Base de conhecimento configurável e estatísticas de acesso',
    changes: [
      'Novo botão nas Configurações para ativar ou esconder a Base de conhecimento sem apagar artigos existentes.',
      'Quando a Base de conhecimento está escondida, deixa de aparecer no menu dos utilizadores e o acesso público aos artigos fica bloqueado.',
      'A página Estatísticas passa a mostrar acessos à plataforma, utilizadores ativos, evolução diária, dispositivos, browsers, utilizadores mais ativos e áreas mais usadas.',
      'O backend passa a registar acessos autenticados às APIs da plataforma para alimentar as estatísticas detalhadas.',
    ],
  },
  {
    version: '1.7.41',
    date: '2026-05-11',
    time: '14:57',
    title: 'Entra ID: todos os utilizadores exceto alunos',
    changes: [
      'A sincronização do Entra ID passa a importar todos os utilizadores ativos, incluindo contas cloud-only sem OU/onPremDN, desde que não sejam alunos.',
      'O login Microsoft deixa de bloquear utilizadores válidos por não pertencerem a uma OU previamente permitida.',
      'O diálogo de sincronização foi clarificado para indicar que os alunos continuam a ser ignorados automaticamente.',
    ],
  },
  {
    version: '1.7.40',
    date: '2026-05-11',
    time: '13:02',
    title: 'Validação clara no novo ticket',
    changes: [
      'A página de criação de tickets passa a mostrar uma caixa com os campos obrigatórios que ainda faltam preencher.',
      'Os campos em falta ficam destacados visualmente, evitando que o botão "Submeter ticket" pareça bloqueado sem explicação.',
    ],
  },
  {
    version: '1.7.39',
    date: '2026-05-11',
    time: '12:46',
    title: 'Mapeamento de Assistente Operacional',
    changes: [
      'Utilizadores sincronizados do Entra ID com departamento "ASSISTENTE OPERACIONAL" passam a receber automaticamente o papel "Não Docente".',
      'A regra aplica-se tanto no login Microsoft como na sincronização/importação de utilizadores do Entra ID.',
      'Ao arrancar, a app corrige também utilizadores já existentes com esse departamento, desde que o papel não esteja bloqueado manualmente.',
    ],
  },
  {
    version: '1.7.38',
    date: '2026-05-11',
    time: '12:00',
    title: 'Instrução de resposta nos emails',
    changes: [
      'Os emails enviados ao utilizador passam a indicar claramente que pode responder ao email para atualizar o pedido de ajuda / ticket.',
      'A indicação aparece nos emails de criação, atualização, atribuição, comentário e alteração de conteúdo do ticket.',
    ],
  },
  {
    version: '1.7.37',
    date: '2026-05-11',
    time: '10:34',
    title: 'Correção do scroll no Chrome',
    changes: [
      'O layout principal passa a ter um contentor de conteúdo dedicado ao scroll, com altura e overflow definidos de forma explícita.',
      'Corrigido um comportamento em que o Chrome podia ficar sem permitir scroll nas páginas, apesar de Safari e iPhone continuarem a funcionar.',
    ],
  },
  {
    version: '1.7.36',
    date: '2026-05-11',
    time: '10:18',
    title: 'Respostas por email via Microsoft Graph',
    changes: [
      'A importação de respostas por email passa a suportar Microsoft Graph, evitando bloqueios de IMAP/password em tenants Microsoft 365 modernos.',
      'Nova configuração MAIL_REPLY_PROVIDER=graph e GRAPH_MAIL_USER para indicar a mailbox de suporte a ler.',
      'O modo IMAP continua disponível como fallback com MAIL_REPLY_PROVIDER=imap.',
      'O botão "Ler respostas" e a sincronização automática passam a indicar nos resultados se a origem usada foi graph ou imap.',
    ],
  },
  {
    version: '1.7.29',
    date: '2026-05-10',
    time: '09:25',
    title: 'Página Sobre — autoria e método de criação',
    changes: [
      'Nova página "Sobre" no menu lateral, a seguir a "Versão / Atualizações".',
      'Descreve o autor, o método de desenvolvimento assistido por IA (Claude Code + ChatGPT/Codex) e as tecnologias utilizadas.',
    ],
  },
  {
    version: '1.7.27',
    date: '2026-05-10',
    time: '08:56',
    title: 'Safe area iOS — cabeçalho e scroll corrigidos',
    changes: [
      'Corrigido: em iPhones com notch ou Dynamic Island, o cabeçalho sobrepunha-se à barra de estado do iOS.',
      'A página de login também passa a respeitar a safe area do topo em todos os iPhones.',
    ],
  },
  {
    version: '1.7.26',
    date: '2026-05-09',
    time: '16:10',
    title: 'Navegação móvel corrigida (logo e menus sempre acessíveis)',
    changes: [
      'Corrigido: na versão móvel (browser iOS/Android e PWA), o topo da página ficava escondido atrás da barra nativa do browser.',
      'Novo layout móvel: botão de menu, logotipo e nome do agrupamento integrados no cabeçalho principal (sempre visível, nunca coberto).',
      'A barra de navegação lateral desliza a partir de baixo do cabeçalho ao tocar no ícone ≡.',
    ],
  },
  {
    version: '1.7.24',
    date: '2026-05-09',
    time: '14:05',
    title: 'App PWA para iOS e Android',
    changes: [
      'O Helpdesk Escolar é agora uma Progressive Web App (PWA) — pode ser instalada diretamente no iPhone/iPad ou Android a partir do browser, sem passar pela App Store ou Play Store.',
      'iOS: no Safari, toca em Partilhar → "Adicionar ao ecrã de início". Android/Chrome: toca nos três pontos → "Instalar app".',
      'Ícone personalizado com letra H no ecrã de início, barra de estado em azul escolar, modo standalone (sem barra do browser).',
    ],
  },
  {
    version: '1.7.23',
    date: '2026-05-09',
    time: '13:30',
    title: 'Cópia automática para OneDrive (Microsoft 365)',
    changes: [
      'Nova secção OneDrive em Backup & Restauro: ativa a cópia automática de cada backup (JSON e ZIP) para o OneDrive de um utilizador da escola.',
      'Usa as credenciais Azure AD já configuradas na app — não é necessário configurar nada separado.',
      'Requer a permissão Files.ReadWrite.All (aplicação) na app registration do Azure AD com consentimento de administrador.',
      'Pasta configurável no OneDrive; os ZIPs vão para uma subpasta full_zips/ dentro da pasta escolhida.',
      'Botão "Testar ligação" verifica as credenciais e cria um ficheiro de teste no OneDrive.',
      'Erros de upload ao OneDrive ficam visíveis no registo de cópias por entrada.',
    ],
  },
  {
    version: '1.7.22',
    date: '2026-05-09',
    time: '11:30',
    title: 'Restauro a partir de ZIP completo',
    changes: [
      'A área de importação aceita agora tanto ficheiros .json (apenas dados) como .zip (completo com anexos).',
      'Ao restaurar um ZIP completo, a base de dados é reposta a partir do tickets.db incluído no ZIP e todos os ficheiros anexados são copiados de volta.',
      'As configurações da aplicação (app_settings.json) e do backup (backup_config.json) são também restauradas do ZIP.',
      'O diálogo de confirmação indica claramente o tipo de ficheiro e o que será substituído.',
      'O resumo pós-restauro inclui o número de ficheiros de anexos recuperados.',
    ],
  },
  {
    version: '1.7.21',
    date: '2026-05-09',
    time: '07:44',
    title: 'Cópias automáticas do ZIP completo para o NAS secundário',
    changes: [
      'Nova opção "Cópias automáticas (ZIP completo)" na configuração de backup — o servidor cria automaticamente um ZIP completo (base de dados + anexos + .env) em cada intervalo configurado.',
      'O ZIP automático é guardado em subpasta "full_zips" dentro do destino principal e, se configurado, copiado para o destino secundário (outro NAS, partilha de rede, etc.).',
      'Número de ZIPs a manter configurável independentemente do número de JSONs.',
      'O registo de cópias identifica as entradas ZIP com etiqueta roxa "ZIP".',
      'Os ZIPs gerados automaticamente são excluídos do conteúdo dos novos ZIPs para evitar recursividade.',
    ],
  },
  {
    version: '1.7.20',
    date: '2026-05-08',
    time: '22:13',
    title: 'Melhorias de backup, pesquisa, SLA e de-escalação',
    changes: [
      'Pesquisa de tickets por título e descrição nas listas do utilizador e do administrador.',
      'Indicador de SLA visível nas listas de tickets — mostra tempo restante ou excedido com código de cor (verde/amarelo/laranja/vermelho).',
      'Botão "Fornecedor resolveu" no detalhe do ticket para marcar de-escalação quando o fornecedor externo resolve o problema.',
      'Botão de teste de SMTP nas configurações — envia email de teste diretamente para o administrador.',
      'Restauro de dados a partir de ficheiro JSON na página de backup — com confirmação em dois passos e resumo dos registos restaurados.',
      'Diálogo de confirmação antes de descarregar o ZIP completo, que inclui o .env com credenciais sensíveis.',
      'Correção: cópias automáticas eram registadas como "manual" em vez de "auto".',
      'Correção: agendador aguardava o intervalo completo antes da primeira cópia automática — passa a executar imediatamente ao arrancar.',
      'Correção: geração do ZIP completo deixa de carregar todos os ficheiros em memória RAM — usa ficheiro temporário em disco.',
      'Sincronização Entra ID: utilizadores removidos do Entra são agora automaticamente desativados.',
      'Hora de atualização adicionada ao rótulo de versão.',
    ],
  },
  {
    version: '1.7.19',
    date: '2026-05-08',
    time: '20:45',
    title: 'Exportação completa para recuperação catastrófica',
    changes: [
      'Novo botão "Descarregar ZIP completo": exporta tudo — base de dados SQLite, todos os ficheiros anexados, logótipo e configurações da aplicação — num único ficheiro ZIP.',
      'O ZIP inclui um ficheiro RESTAURO.txt com instruções passo a passo para repor o helpdesk numa instalação limpa.',
      'Se estiver configurado um destino secundário, é possível guardar o ZIP diretamente nesse local a partir da interface.',
      'Nota: o ficheiro .env não está incluído no ZIP porque contém segredos — deve ser guardado separadamente.',
    ],
  },
  {
    version: '1.7.18',
    date: '2026-05-08',
    time: '19:27',
    title: 'Registo persistente de backups e destino secundário',
    changes: [
      'O registo de cópias de segurança é agora persistente no servidor — as entradas mantêm-se entre sessões e recarregamentos da página.',
      'Adicionado campo "Destino secundário": após criar a cópia no local principal, o servidor copia automaticamente o ficheiro para um segundo caminho (partilha de rede, disco externo, etc.).',
      'O registo indica se a cópia foi manual ou automática, os locais onde foi guardada e eventuais erros no destino secundário.',
    ],
  },
  {
    version: '1.7.17',
    date: '2026-05-08',
    time: '08:03',
    title: 'Notificação ao fornecedor quando ticket escalado é atualizado',
    changes: [
      'Quando o assunto ou a descrição de um ticket que já foi escalado para o fornecedor são alterados pelo administrador, é enviado automaticamente um email ao fornecedor com o conteúdo atualizado.',
      'O email indica quem fez a alteração e inclui a descrição atual do pedido.',
    ],
  },
  {
    version: '1.7.16',
    date: '2026-05-08',
    time: '07:19',
    title: 'Escalação na criação e edição de conteúdo pelo administrador',
    changes: [
      'Ao criar um ticket, o administrador pode ativar "Escalar imediatamente para fornecedor" — o email de escalação é enviado ao fornecedor externo logo após a criação, sem passos extra.',
      'O administrador pode editar o assunto e a descrição de qualquer ticket através do botão Editar no topo do ticket.',
      'Quando o conteúdo é alterado, todos os participantes (autor, técnico, grupo, pessoas em conhecimento) recebem um email de notificação identificando quem fez a alteração.',
    ],
  },
  {
    version: '1.7.15',
    date: '2026-05-07',
    time: '21:08',
    title: 'Notificações automáticas para quem responde a um ticket',
    changes: [
      'Quem responde a um ticket passa a ser automaticamente adicionado às pessoas em conhecimento, ficando assim a receber todas as notificações seguintes (novas respostas, alterações de estado, fecho do ticket).',
      'Este comportamento aplica-se a qualquer utilizador que não seja já o autor, o técnico atribuído ou esteja explicitamente em conhecimento.',
    ],
  },
  {
    version: '1.7.14',
    date: '2026-05-07',
    time: '07:36',
    title: 'Aviso de modo de demonstração',
    changes: [
      'Quando o utilizador entra em modo de demonstração, aparece um aviso persistente no topo de todas as páginas a informar que os pedidos não serão processados e a indicar como entrar com a conta da escola.',
      'O aviso inclui um botão "Entrar" que redireciona diretamente para o ecrã de login.',
      'O aviso adapta-se ao modo escuro.',
    ],
  },
  {
    version: '1.7.13',
    date: '2026-05-06',
    time: '23:41',
    title: 'Pré-visualização de imagens e PDFs nos tickets',
    changes: [
      'Imagens anexadas aparecem como miniaturas diretamente no ticket — clicar abre a imagem em popup a ecrã inteiro.',
      'PDFs e outros ficheiros abrem num novo separador do browser ao clicar.',
      'As miniaturas são carregadas automaticamente quando o ticket é aberto.',
    ],
  },
  {
    version: '1.7.12',
    date: '2026-05-06',
    time: '23:19',
    title: 'Correções de upload e download de anexos',
    changes: [
      'O backend passa a aceitar qualquer formato de imagem (incluindo HEIC e WebP de dispositivos iOS/Android) além de PDF.',
      'A opção de anexar ficheiro no formulário de novo ticket passa a abrir a galeria completa do dispositivo móvel.',
      'Se um anexo falhar no upload, o ticket é criado na mesma e o utilizador é avisado do ficheiro que falhou.',
      'O download de anexos ficou mais fiável: o link temporário permanece válido durante 10 segundos para compatibilidade com todos os browsers.',
    ],
  },
  {
    version: '1.7.11',
    date: '2026-05-06',
    time: '22:54',
    title: 'Correções de anexos, mobile e branding do login',
    changes: [
      'Clicar num anexo já não devolve "Not authenticated" — o download é agora feito com o token de sessão.',
      'O botão "Submeter ticket" deixou de ficar bloqueado após escolher um ficheiro da galeria no telemóvel.',
      'A opção de receber atualizações por email fica ativa por defeito ao criar um ticket.',
      'Ficheiros da galeria iOS (HEIC e outros formatos móveis) passam a ser aceites como anexos.',
      'Página de login: título alterado para "Centro de Apoio Digital do Agrupamento".',
      'Painel lateral do login mostra agora o nome do agrupamento e o endereço www.queiroz.pt de forma destacada.',
      'Cada funcionalidade destacada no login tem agora uma cor e ícone distintos.',
      'Pesquisa de pessoas em conhecimento no detalhe do ticket passa a filtrar por endereço de email.',
    ],
  },
  {
    version: '1.7.10',
    date: '2026-05-06',
    time: '22:16',
    title: 'Diagnóstico das respostas por email',
    changes: [
      'Os emails enviados passam a definir explicitamente o Reply-To para a caixa configurada em MAIL_FROM.',
      'A sincronização IMAP passa a registar nos logs se encontrou emails não lidos, se ignorou mensagens sem marcador de ticket e se importou respostas com sucesso.',
      'Erros de ligação, autenticação ou seleção da pasta IMAP passam a ficar visíveis nos logs do backend.',
    ],
  },
  {
    version: '1.7.9',
    date: '2026-05-06',
    time: '21:43',
    title: 'Respostas por email atualizam o ticket',
    changes: [
      'Quando a caixa IMAP de respostas está configurada, respostas a emails com o assunto [Ticket #ID] passam a ser importadas automaticamente como comentários públicos no ticket.',
      'Cada resposta recebida por email atualiza a data do ticket, cria um registo no histórico e evita duplicados através do Message-ID.',
      'Os restantes participantes do ticket são notificados quando chega uma nova resposta por email.',
    ],
  },
  {
    version: '1.7.8',
    date: '2026-05-06',
    time: '21:05',
    title: 'Correção da pesquisa em conhecimento por utilizador',
    changes: [
      'No detalhe do ticket, o campo Em conhecimento passa a filtrar sugestões pelo nome, email, prefixo do email e nome de utilizador.',
      'Ao escrever diretamente um utilizador como pedropereira, o botão Adicionar passa a identificar esse utilizador quando a correspondência é exata ou única.',
    ],
  },
  {
    version: '1.7.7',
    date: '2026-05-06',
    time: '20:28',
    title: 'Pesquisa por utilizador nas pessoas em conhecimento',
    changes: [
      'A gestão de membros dos grupos internos passa a permitir pesquisar utilizadores por nome, email ou nome de utilizador.',
      'Ao criar um novo ticket, o campo Dar conhecimento a mostra também o nome de utilizador nos resultados.',
      'Na página de detalhe do ticket, a secção Em conhecimento passa a aceitar seleção por nome, email ou nome de utilizador.',
    ],
  },
  {
    version: '1.7.6',
    date: '2026-05-06',
    time: '19:52',
    title: 'Gestão de pessoas em conhecimento no ticket',
    changes: [
      'O autor do ticket e qualquer técnico ou administrador podem agora adicionar e remover pessoas em conhecimento diretamente na página de detalhe, sem ser necessário recriar o ticket.',
      'Campo de pesquisa por nome substitui a lista fixa: basta escrever parte do nome para filtrar os utilizadores disponíveis.',
      'Cada adição ou remoção fica registada no histórico do ticket com o nome da pessoa e quem fez a alteração.',
    ],
  },
  {
    version: '1.7.5',
    date: '2026-05-06',
    time: '19:14',
    title: 'Correção do modo escuro no login',
    changes: [
      'Quando o modo escuro é ativado no ecrã de login, toda a área de entrada passa a usar fundo, cartões, bordas e texto escuros coerentes.',
      'Melhorado o contraste dos textos no login escuro para evitar letras cinzentas sobre fundo claro.',
    ],
  },
  {
    version: '1.7.4',
    date: '2026-05-06',
    time: '08:49',
    title: 'Escolha de tema no login',
    changes: [
      'Página de login continua a abrir em modo claro por defeito.',
      'Adicionada opção visível Modo escuro com escolha Sim / Não no ecrã de entrada.',
      'A escolha de modo escuro no login deixa de prender o ecrã de entrada em escuro nas visitas seguintes.',
    ],
  },
  {
    version: '1.7.3',
    date: '2026-05-06',
    time: '08:31',
    title: 'Criação de tickets e login claro',
    changes: [
      'Administradores podem atribuir logo um novo ticket a pessoas em conhecimento e a equipas internas.',
      'Ao escolher equipas internas na criação do ticket, os membros passam a acompanhar o pedido e recebem notificações.',
      'A sincronização Entra passa a correr automaticamente durante a noite por defeito.',
      'A página de login abre sempre em modo claro, independentemente da preferência usada dentro da aplicação.',
      'Ecrã de entrada mais compacto, com menos espaço vazio no topo e logotipo do agrupamento maior.',
      'Botão principal de entrada renomeado para email ou conta da escola e login local escondido numa opção secundária.',
      'Referências a Active Directory removidas da área visível do login.',
    ],
  },
  {
    version: '1.7.2',
    date: '2026-05-06',
    time: '07:58',
    title: 'Categorias, técnicos ativos e tema',
    changes: [
      'Categorias padrão atualizadas para Inovar, Mail e Teams, Internet e Wi-Fi, Computadores, Impressoras, Projetores, Passwords e Outros.',
      'Cada categoria padrão recebe um ícone simples e uma cor distinta.',
      'A categoria genérica Apoio Técnico deixa de ser criada por defeito e é removida automaticamente quando não tem tickets associados.',
      'O campo Atribuído a passa a mostrar apenas técnicos ativos; administradores, direção e docentes deixam de aparecer como responsáveis diretos.',
      'Regras de encaminhamento automático só aceitam responsáveis que sejam técnicos ativos.',
      'Opção de manter o modo escuro no login tornada visível no ecrã de entrada e no topo da aplicação.',
    ],
  },
  {
    version: '1.7.1',
    date: '2026-05-06',
    time: '07:23',
    title: 'Utilizadores manuais e emails institucionais',
    changes: [
      'Adição manual de utilizadores com nome, email, papel, departamento, estado e palavra-passe definida pelo administrador.',
      'Autenticação local para utilizadores que não existam no Entra ID.',
      'Sincronização Entra passa a preferir aliases institucionais @queiroz.pt em vez de endereços @onmicrosoft.com.',
      'Botões de cancelar e guardar da sincronização Entra colocados também no topo da janela.',
      'Página de entrada com instruções de login e aviso sobre modo escuro.',
      'Ao ativar modo escuro, a aplicação pergunta se deve manter esse modo no ecrã de login.',
      'Regra de manutenção: cada atualização enviada para GitHub deve acrescentar versão e alterações nesta página.',
    ],
  },
  {
    version: '1.7.0',
    date: '2026-05-05',
    time: '22:37',
    title: 'Participantes, notificações e sincronização Entra',
    changes: [
      'Opção para dar conhecimento a pessoas ao criar um ticket.',
      'Participantes podem acompanhar, responder e anexar informação ao ticket.',
      'Opção explícita para o autor receber ou não atualizações por email.',
      'Sincronização Entra com seleção de OUs e exclusão de alunos.',
      'Campo Departamento / OU editável na gestão de utilizadores.',
      'Página de versão e histórico de atualizações.',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-05-05',
    time: '07:52',
    title: 'Escalação e gestão em lote',
    changes: [
      'Escalação de tickets para fornecedor externo configurável.',
      'Ações em lote para arquivar ou apagar tickets selecionados.',
      'Modo demo escondido até ser solicitado no ecrã de login.',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-05-04',
    time: '20:14',
    title: 'Administração escolar',
    changes: [
      'Gestão de escolas, categorias e grupos internos.',
      'Sincronização de utilizadores com Microsoft Entra ID.',
      'Permissões por papel com bloqueio manual de administradores e técnicos.',
      'Configuração de logotipo e favicon do agrupamento.',
    ],
  },
]

export function versionLabel() {
  return `v${APP_VERSION} · ${APP_VERSION_DATE} ${APP_VERSION_TIME}`
}
