export const APP_VERSION = '2.12.1'
export const APP_VERSION_DATE = '2026-10-06'
export const APP_VERSION_TIME = '12:50'

export const RELEASE_NOTES = [
  {
    version: '2.12.1',
    date: '2026-10-06',
    time: '12:50',
    title: 'Quem pediu ajuda sabe que o pedido está a ser acompanhado',
    changes: [
      'Quando um pedido está há 7 dias à espera da equipa, quem o fez também recebe um email: o pedido não foi esquecido, foi pedido o ponto de situação à equipa e não será fechado enquanto estiver à espera de resposta.',
    ],
  },
  {
    version: '2.12.0',
    date: '2026-10-06',
    time: '12:48',
    title: 'Pedidos à espera da equipa já não fecham sozinhos',
    changes: [
      'Um ticket só é fechado automaticamente por inatividade quando a equipa respondeu por último e quem pediu ajuda não voltou a responder.',
      'Se foi quem pediu ajuda a responder por último (ou a equipa ainda não respondeu), o ticket nunca fecha sozinho: ao fim de 7 dias sem atividade, a equipa responsável recebe um email a pedir o ponto de situação, com a última mensagem. Repete-se a cada 7 dias enquanto não houver resposta.',
    ],
  },
  {
    version: '2.11.2',
    date: '2026-10-06',
    time: '12:41',
    title: 'O servidor já não fica bloqueado',
    changes: [
      'Corrigido: uma entrada com Microsoft sem resposta podia deixar o helpdesk inteiro parado (ninguém conseguia entrar, emails e lembretes paravam). Os pedidos à Microsoft passam a ter limite de tempo e já não bloqueiam o resto da aplicação.',
      'Se o servidor deixar de responder durante 3 minutos, reinicia-se sozinho e regista nos logs onde ficou bloqueado.',
    ],
  },
  {
    version: '2.11.1',
    date: '2026-10-06',
    time: '12:38',
    title: 'Diagnóstico da entrada com Microsoft',
    changes: [
      'Quando a entrada com a conta Microsoft falha, o motivo fica registado nos logs do servidor (segredo expirado, endereço de retorno errado, utilizador fora das unidades permitidas, ...).',
      'Se a Microsoft recusar a entrada, aparece uma mensagem clara em vez de um erro técnico.',
    ],
  },
  {
    version: '2.11.0',
    date: '2026-09-29',
    time: '17:17',
    title: 'Caixa de entrada: responder, reencaminhar e eliminar',
    changes: [
      'Na caixa de entrada é possível responder, responder a todos, reencaminhar e eliminar emails. As mensagens saem do endereço do helpdesk, com o nome de quem respondeu no fim; a mensagem original vai citada.',
      'Ao reencaminhar, os destinatários escolhem-se da lista de pessoas sincronizadas (docentes, funcionários e alunos) — basta escrever parte do nome ou do email — ou escrevendo um endereço completo. Os anexos seguem com a mensagem.',
      'Corrigido: abrir alguns emails dava "Erro no servidor" (o conteúdo dos anexos era descarregado logo ao abrir, e alguns erros de ligação não eram tratados). Agora só se leem os nomes dos anexos, as imagens das assinaturas não aparecem na lista, e se algo falhar a mensagem explica porquê.',
    ],
  },
  {
    version: '2.10.2',
    date: '2026-09-29',
    time: '17:12',
    title: 'Aviso para alunos no contacto sem acesso ao mail',
    changes: [
      'Em "Não tenho acesso ao mail institucional", ao escolher "Aluno" aparece um aviso: o formulário é só para problemas de acesso ao email institucional e ao Microsoft Teams.',
    ],
  },
  {
    version: '2.10.1',
    date: '2026-09-29',
    time: '16:56',
    title: 'Quadro: escolher os tipos de pedido a mostrar',
    changes: [
      'No Quadro, o botão "Tipos de pedido" abre a lista das categorias com um visto: tire o visto às que não quer ver. A escolha fica guardada neste dispositivo e mostra quantos pedidos há de cada tipo.',
      'Botões "Mostrar todos" e "Esconder todos" para mudar tudo de uma vez.',
    ],
  },
  {
    version: '2.10.0',
    date: '2026-09-29',
    time: '16:12',
    title: 'Aviso de novidades e quadro no telemóvel',
    changes: [
      'Aviso de novidades: uma janela com as alterações mais importantes, mostrada uma vez a cada pessoa quando entra (em qualquer dispositivo). Liga-se e edita-se em Configurações → Novidades, com pré-visualização; "Publicar como novas" volta a mostrá-la a todos.',
      'Quadro: filtro por tipo de pedido (categoria).',
      'Quadro no telemóvel: separadores por estado e uma coluna de cada vez, em largura total; o estado muda-se no menu de cada cartão.',
      'Novo cartão para o site do Agrupamento (docs/site-agrupamento), mais moderno e adaptado a telemóvel, a mostrar ajuda.queiroz.pt.',
    ],
  },
  {
    version: '2.9.2',
    date: '2026-09-29',
    time: '16:07',
    title: 'Quadro mais compacto',
    changes: [
      'As cinco colunas do Quadro cabem no ecrã de um portátil (a partir de 1280 px); só em ecrãs estreitos passa a deslizar para o lado.',
      'Cartões mais compactos e uma frase no topo a explicar o Quadro.',
    ],
  },
  {
    version: '2.9.1',
    date: '2026-09-29',
    time: '16:04',
    title: 'O meu perfil e estatísticas corrigidas',
    changes: [
      'Clicar no seu avatar (canto superior direito) abre um menu com o seu nome, email e papel, e ligações para "O meu perfil", "As minhas notificações", modo escuro e terminar sessão.',
      'Nova página "O meu perfil": cada pessoa pode mudar a forma como o seu nome aparece nos tickets, com pré-visualização do nome longo e do nome curto (com a etiqueta do grupo, ex.: 510 FQ). A sincronização com o Microsoft 365 deixa de o alterar; há um botão para voltar ao nome da conta da escola.',
      'Corrigido: o gráfico "Tickets criados vs resolvidos" podia mostrar mais resolvidos do que criados. Agora mostra, para os tickets criados em cada semana, quantos desses já estão resolvidos ou fechados.',
      'Corrigido: a data de resolução dos tickets antigos usava a última mudança de estado (ex.: o fecho automático por inatividade) em vez do momento em que foram resolvidos. Foi recalculada a partir do histórico.',
      'O cartão "Total de tickets" dizia "este mês", mas mostra o total.',
    ],
  },
  {
    version: '2.9.0',
    date: '2026-09-29',
    time: '15:53',
    title: 'Caixa de entrada, quadro, avaliações, menções e muito mais',
    changes: [
      'Caixa de entrada do helpdesk dentro da aplicação: ler os emails, criar um ticket a partir de um email (o remetente fica como requerente e os anexos passam para o ticket) ou juntá-lo a um ticket existente, marcar como lido e arquivar. Nova permissão "Ver a caixa de entrada do helpdesk" (técnicos e Equipa TIC).',
      '"Os meus tickets" com novo aspeto, como no Painel inicial: cor por estado, escola, categoria, requerente e há quanto tempo. A tabela compacta continua disponível no botão ao lado de "Categorias".',
      'Quadro (Kanban) para a equipa: tickets por estado; arraste um cartão para mudar o estado.',
      'Avaliação do atendimento: quando o pedido é resolvido ou fechado, o requerente dá 1 a 5 estrelas e um comentário (também a partir do email). As avaliações aparecem nas Estatísticas e no ticket.',
      'Menções: escreva @ numa resposta ou nota para mencionar alguém; a pessoa recebe um aviso (só se puder ler essa mensagem).',
      'Colar capturas de ecrã diretamente na resposta ou ao criar um ticket; botão "Foto" no telemóvel/tablet.',
      'Respostas-modelo editáveis em Configurações → Respostas-modelo, cada uma pode também mudar o estado.',
      'Relatório mensal para a Direção: enviado por email no dia 1 de cada mês (Configurações → Relatório mensal) e disponível para imprimir nas Estatísticas.',
      'Manutenção planeada: tickets criados automaticamente todas as semanas, meses, períodos ou anos (ex.: verificar projetores).',
      '"Não tenho acesso ao mail institucional" também para alunos: número do cartão (a12345), ano, turma e escola; o email passa a ser opcional para alunos.',
      'Privacidade: os emails das sugestões e as OUs do Active Directory deixam de aparecer nas configurações públicas.',
    ],
  },
  {
    version: '2.8.1',
    date: '2026-09-29',
    time: '15:14',
    title: 'Conversas privadas numa só caixa',
    changes: [
      'Cada conversa privada fica numa única caixa com todas as mensagens encadeadas, mesmo que haja respostas públicas pelo meio. A caixa aparece no ponto da mensagem mais recente, com a caixa de resposta no fundo.',
      'Os nomes das pessoas da conversa aparecem sempre pela mesma ordem.',
    ],
  },
  {
    version: '2.8.0',
    date: '2026-09-29',
    time: '15:12',
    title: 'Menos emails e empresa de apoio com a conversa toda',
    changes: [
      'Empresa de apoio: ao reportar um ticket, o email leva a descrição e toda a conversa pública trocada até aí (sem notas internas nem mensagens privadas), e a lista de anexos. Cada nova resposta ou reenvio também leva o histórico.',
      'A empresa de apoio deixa de receber um email a cada alteração (ex.: prioridade): recebe as respostas e o fecho do pedido.',
      'Mudanças de estado: só o requerente é avisado, e só quando o pedido fica a aguardar a resposta dele, é resolvido ou fechado. A equipa deixa de receber estes emails (pode ligá-los nas suas preferências).',
      'Responder e mudar o estado ao mesmo tempo gera um só email, com a resposta e o novo estado.',
      'Mudar a prioridade ou o grupo deixa de enviar emails; só quem passa a ser responsável é avisado. Ações em massa só avisam o requerente quando o ticket é resolvido ou fechado.',
      'Ninguém recebe aviso das suas próprias ações. Editar uma resposta ou anexar um ficheiro deixa de reenviar emails.',
      'Nova página "As minhas notificações" (clique no seu nome na barra lateral, ou no sino): escolha o que recebe por email e como notificação — tickets atribuídos, respostas, mensagens privadas, mudanças de estado, lembretes e chat.',
      'Os assuntos dos emails passam a estar em português (antes terminavam em "Commented", "Updated"…).',
    ],
  },
  {
    version: '2.7.1',
    date: '2026-09-29',
    time: '12:38',
    title: 'Estatísticas: tickets resolvidos contados corretamente',
    changes: [
      'Corrigido: o gráfico "Tickets criados vs resolvidos" só contava tickets no estado "Resolvido" e pela data da última alteração. Agora conta resolvidos e fechados, na semana em que foram resolvidos/fechados.',
      'Cada ticket passa a guardar a data em que foi resolvido ou fechado (para os tickets antigos é recuperada do histórico).',
      'O cartão "Resolvidos/fechados" soma os dois estados, e o "Tempo médio" até à resolução passa a ser calculado (últimos 90 dias).',
    ],
  },
  {
    version: '2.7.0',
    date: '2026-09-29',
    time: '12:28',
    title: 'Mais rápido, conversas privadas mais práticas e manutenção',
    changes: [
      'Conversas privadas: cada conversa tem a sua própria caixa para responder logo ali (vai para todas as pessoas da conversa). O cabeçalho mostra quem participa sem cortar o texto.',
      'Corrigido: na lista de tickets, o estado "A aguardar utilizador" ficava por cima da prioridade. Na tabela aparece "A aguardar" (o nome completo aparece ao passar o rato).',
      'Modo escuro: os estados dos tickets deixam de aparecer com fundo claro.',
      'As reações carregam muito mais depressa em tickets com muitas respostas; várias verificações de acesso ficaram mais leves.',
      'Novos índices na base de dados: listas, contadores e tickets abrem mais depressa à medida que os dados crescem.',
      'Os filtros "Fora do prazo" e "A expirar" deixam de carregar todos os tickets abertos.',
      'Registo de acessos gravado em lotes (sem atrasar cada pedido) e limpo automaticamente ao fim de 180 dias.',
      'Listas de tickets desenham só a vista visível (tabela ou cartões): mais leves em iPads e telemóveis.',
      'Interruptores (toggles) usáveis com o teclado e anunciados aos leitores de ecrã.',
      'Corrigido: os botões das notificações push no menu do sino podiam ficar sempre desativados.',
      'A chave de sessão deixa de ficar escrita nos registos do servidor.',
      'Instalação: versões exatas das bibliotecas em cada build (npm ci), ficheiros .dockerignore, fuso horário de Lisboa e registos dos contentores com tamanho limitado.',
      'Testes automáticos do servidor e verificação de tipos do ecrã.',
    ],
  },
  {
    version: '2.6.0',
    date: '2026-09-29',
    time: '12:18',
    title: 'Mensagens privadas a várias pessoas, preto puro e menos falhas silenciosas',
    changes: [
      'Mensagens privadas a várias pessoas ao mesmo tempo: escolha um ou mais destinatários. A conversa aparece num bloco próprio e "Responder a todos em privado" responde a todo o grupo. Só o autor e os destinatários a veem.',
      'A Direção pode receber mensagens privadas (aparece num grupo próprio na lista) e responder-lhes em privado, também por email.',
      'Modo escuro "preto puro" (true black): em Configurações → Organização e aspeto, escolha entre cinzento escuro e preto puro. Aplica-se a quem ativar o modo escuro.',
      'Depois de cada atualização do servidor, as páginas abertas voltam a receber mensagens em tempo real sem ser preciso recarregar (e atualizam o que mostram).',
      'Password errada no login: a mensagem de erro fica visível (a página já não recarrega).',
      'Uma falha momentânea de rede ou o servidor a reiniciar já não termina a sessão.',
      'Clicar no próprio nome na barra lateral já não termina a sessão; o botão de sair pede confirmação.',
      'Abrir outro ticket a partir de um ticket (ex.: link no chat) mostra de facto o novo ticket.',
      'Uma resposta de outra pessoa já não apaga a pesquisa de técnico que estava a escrever.',
      '"Os meus tickets" mostra quantos tickets há e tem o botão "Carregar mais" (antes só apareciam os primeiros 50).',
      'Quando uma ação falha (mudar papel, apagar, guardar configurações…) aparece uma mensagem de erro, em vez de parecer que resultou. As confirmações usam janelas da aplicação, também no modo escuro.',
      'Depois de uma atualização, um separador antigo que já não encontra as páginas recarrega sozinho.',
      'Corrigido: a página de cópias de segurança mostrava o OneDrive sempre como desligado.',
      'Mensagens de erro do servidor que estavam em inglês passam a estar em português.',
    ],
  },
  {
    version: '2.5.0',
    date: '2026-09-29',
    time: '11:37',
    title: 'Dados mais seguros e fiáveis',
    changes: [
      'Apagar um ticket apaga também tudo o que lhe pertence (lembretes, reações, marcas de lido, anexos no disco). Corrigido: apagar um ticket com um lembrete pendente fazia parar todos os lembretes.',
      'Os lembretes são enviados um a um: um lembrete com problema já não impede os outros, e nenhum é enviado duas vezes.',
      'Cópias de segurança: o JSON passa a incluir todas as tabelas (papéis, grupos, chat, histórico, base de conhecimento…). O restauro do ZIP repõe a base de dados inteira, exatamente como estava, e guarda antes uma cópia da atual.',
      'A cópia da base de dados no ZIP é feita de forma consistente, mesmo com a aplicação em uso. O ZIP deixa de incluir palavras-passe e chaves.',
      'A cada arranque do servidor é guardada automaticamente uma cópia da base de dados (as 5 últimas ficam em data/snapshots).',
      'Base de dados em modo WAL: menos esperas e sem erros "database is locked" nas horas de maior uso. As regras de integridade passam a ser aplicadas.',
      'Falhas nos processos automáticos (backups, emails, lembretes, sincronização) ficam registadas; um backup automático que falhe aparece no "Registo de cópias".',
      'As configurações são gravadas de forma segura (nunca ficam a meio) e um aviso do Teams já não desfaz alterações feitas ao mesmo tempo.',
      'Respostas por email só são marcadas como lidas depois de guardadas: se algo falhar, são importadas na ronda seguinte.',
      'Apagar uma categoria com tickets mostra uma mensagem clara em vez de dar erro. Apagar grupos ou escolas em uso deixa de deixar ligações partidas.',
    ],
  },
  {
    version: '2.4.0',
    date: '2026-09-29',
    time: '11:22',
    title: 'Reforço de segurança',
    changes: [
      'Respostas por email: só são aceites de quem faz parte do ticket (requerente, técnicos atribuídos, observadores ou equipa de apoio). Fechar ou resolver por email só é possível ao requerente, à equipa de apoio ou à empresa de apoio. Frases como "não está resolvido" já não fecham o ticket.',
      'Modo demo: passa a existir só o perfil de docente (os perfis de técnico e administrador davam acesso a dados reais).',
      'Anexos: só são aceites imagens, PDF, Office, OpenDocument, texto e ZIP, com verificação do conteúdo real do ficheiro. Os anexos deixam de estar acessíveis por link público; só se abrem a partir do ticket.',
      'Os docentes deixam de poder alterar o estado, a prioridade ou a atribuição de um ticket através da API.',
      'Os emails enviados passam a proteger o texto introduzido pelos utilizadores (sem HTML injetado).',
      'Proteção contra tentativas repetidas de entrada: após 10 falhas em 15 minutos é preciso aguardar.',
      'Chave de sessão: se não estiver definida uma chave forte, é gerada automaticamente e guardada no servidor.',
      'Bibliotecas do servidor atualizadas (FastAPI, Starlette, Uvicorn, Jinja2, JWT, python-multipart, requests) com correções de segurança.',
    ],
  },
  {
    version: '2.3.1',
    date: '2026-09-28',
    time: '12:00',
    title: 'Reações sempre visíveis',
    changes: [
      'Corrigido: o botão para reagir só aparecia ao passar o rato e, por um erro, ficava invisível. Agora cada mensagem mostra sempre o botão "Reagir" (ou só o ícone, quando já há reações).',
      'A descrição do pedido (a primeira mensagem do ticket) também aceita reações.',
    ],
  },
  {
    version: '2.3.0',
    date: '2026-09-28',
    time: '11:30',
    title: 'Reações com emojis',
    changes: [
      'É possível reagir com emojis às respostas dos tickets e às mensagens do chat: 👍 ❤️ 😂 😮 🙏 ✅ 👀 🎉.',
      'As reações aparecem por baixo da mensagem com o número de pessoas; ao passar o rato vê-se quem reagiu. Clicar de novo retira a reação.',
      'Aparecem em tempo real para quem está a ver o ticket ou a conversa.',
      'Seguem as regras de privacidade: numa nota interna só técnicos reagem e veem; numa mensagem privada só as duas pessoas.',
    ],
  },
  {
    version: '2.2.7',
    date: '2026-09-28',
    time: '10:00',
    title: '"Os meus tickets": colunas fixas, lido/não lido e apagar',
    changes: [
      'A tabela de "Os meus tickets" passa a ter larguras fixas por coluna: nunca sai do ecrã, o assunto tem mais espaço e as categorias compridas (ex.: "Apoio Técnico") ficam dentro da coluna.',
      'Em cada ticket (tabela, cartões e página do ticket): botão para marcar como lido ou não lido manualmente.',
      'Administradores: botão para apagar um ticket (na lista e na página do ticket), com confirmação. Apaga também as respostas e os anexos.',
      'Corrigida a faixa mais escura que aparecia na coluna Estado nos tickets não lidos.',
    ],
  },
  {
    version: '2.2.6',
    date: '2026-09-27',
    time: '17:00',
    title: 'Tabelas de tickets arrumadas no computador',
    changes: [
      'Nas tabelas, o lembrete passa a ser só o ícone ⏰ junto ao número (a data aparece ao passar o rato); nos cartões do iPad e telemóvel continua a etiqueta com a data.',
      '"Os meus tickets" e a Gestão de tickets cabem na largura do ecrã, sem colunas cortadas nem deslizar para o lado.',
      'Gestão de tickets: a escola, a categoria e a última atualização aparecem por baixo do assunto; listas de estado, responsável e grupo mais compactas (com nomes curtos); Emails passa a um ícone de sino. Abaixo de 1500 px de largura aparecem os cartões.',
      'Corrigido: nomes cortados com "…" em ecrãs de alta resolução em vez de passarem à forma curta; coluna Emails desalinhada para técnicos.',
    ],
  },
  {
    version: '2.2.5',
    date: '2026-09-27',
    time: '16:00',
    title: 'iPad e telemóvel: listas de tickets em cartões',
    changes: [
      '"Os meus tickets" e a Gestão de tickets deixam de usar a tabela larga em iPad e telemóvel: cada ticket aparece num cartão (como numa caixa de email) com ID, lembrete, assunto, estado, prioridade, escola, categoria e solicitante. Em ecrãs grandes continua a tabela.',
      'No iPad os cartões aparecem em duas colunas; no telemóvel numa só.',
      'Barra de filtros arrumada no telemóvel; os contadores do Painel inicial passam a duas linhas em vez de ficarem cortados; o logotipo nas Configurações já não sai do ecrã.',
      'Os cartões da Gestão de tickets também mostram os não lidos e deixam de sair do ecrã no telemóvel.',
    ],
  },
  {
    version: '2.2.4',
    date: '2026-09-27',
    time: '15:00',
    title: 'Lembrete gravado automaticamente',
    changes: [
      '"Lembrar-me deste ticket" grava sozinho: ao ligar fica marcado para amanhã às 9h; mudar o dia, a hora ou usar um atalho atualiza-o na hora; desligar cancela-o. Deixa de haver botão "Guardar lembrete".',
      'Ao voltar ao ticket, o interruptor aparece ligado com a data e a hora marcadas, e a indicação "Guardado — recebe um email e uma notificação a…".',
      'Enviar uma resposta já não mexe no lembrete.',
    ],
  },
  {
    version: '2.2.3',
    date: '2026-09-27',
    time: '14:30',
    title: 'Lembretes guardados sem ser preciso responder',
    changes: [
      'Corrigido: o lembrete só ficava gravado ao enviar uma resposta; sem texto, o botão Enviar estava desativado e o lembrete perdia-se.',
      'Novo botão "Guardar lembrete" dentro de "Lembrar-me deste ticket": grava logo, sem escrever resposta.',
      'Os lembretes marcados aparecem no ticket ("Lembrete marcado para segunda-feira, 28 de setembro às 09:00") com a opção Cancelar, e a etiqueta ⏰ aparece em todas as listas.',
      'Continua a ser possível ligar o lembrete ao enviar uma resposta.',
    ],
  },
  {
    version: '2.2.2',
    date: '2026-09-27',
    time: '13:30',
    title: 'Pesquisa corrigida e lembretes visíveis em todo o lado',
    changes: [
      'Corrigido: a caixa de pesquisa no topo do ecrã abria "Os meus tickets" mas ignorava o texto pesquisado.',
      'A pesquisa passa a ignorar acentos e maiúsculas ("configuracao" encontra "Configuração") e procura também pelo número do ticket (12, T-12, #12), pela pessoa que fez o pedido, pela escola, pela categoria e pelo texto das respostas (as notas internas só para técnicos).',
      'Corrigido: a etiqueta de lembrete ("⏰ amanhã 09:00") não aparecia na Gestão de tickets nem no Painel inicial; agora aparece em todas as listas. A Gestão de tickets mostra também os tickets não lidos.',
      'Corrigido: "Próxima segunda" saltava uma semana quando usado ao domingo.',
    ],
  },
  {
    version: '2.2.1',
    date: '2026-09-27',
    time: '12:30',
    title: 'Escola com iniciais em "Os meus tickets"',
    changes: [
      'A coluna Escola mostra as iniciais da escola numa etiqueta (EQ, VG, PN); o nome completo aparece ao passar o rato.',
    ],
  },
  {
    version: '2.2.0',
    date: '2026-09-27',
    time: '12:00',
    title: 'Tickets lidos e não lidos, como no email',
    changes: [
      'Em "Os meus tickets", os tickets com novidades que ainda não abriu aparecem a negrito, com um ponto azul e fundo destacado; deixam de estar destacados quando os abre.',
      'Conta como novidade uma resposta de outra pessoa que possa ver (as notas internas só contam para técnicos e as mensagens privadas só para quem as recebe) e um ticket novo de outra pessoa. As suas próprias respostas nunca contam.',
      'Botão "N não lidos" para mostrar só os tickets por ler, "Marcar todos como lidos" e, dentro de cada ticket, "Marcar como não lido".',
      'Lembretes mais visíveis: a seguir ao ID aparece uma etiqueta com a data e a hora do lembrete (ex.: "⏰ 02/03 09:00"), só para quem o criou.',
      'A lista atualiza-se sozinha quando chega uma nova resposta.',
    ],
  },
  {
    version: '2.1.2',
    date: '2026-09-27',
    time: '11:00',
    title: 'Nome completo quando cabe, nome curto quando não cabe',
    changes: [
      'Os nomes das pessoas aparecem completos (ex.: "Maria Leonor Marinho Nunes Serra Docente-510 - Física e Química") sempre que há espaço, e passam automaticamente à forma curta ("Maria Serra · 510 FQ") só quando não cabem — por exemplo em ecrãs pequenos, no telemóvel, na barra lateral ou nas colunas das listas.',
      'O ajuste acontece sozinho ao redimensionar a janela; o nome completo aparece sempre ao passar o rato.',
      'Aplicado na conversa dos tickets, em "Aberto por", nos detalhes (solicitante, responsáveis, em conhecimento), em "Os meus tickets", na Gestão de tickets, na barra lateral e no chat.',
      'Corrigido: no telemóvel, o painel de detalhes do ticket saía para fora do ecrã.',
    ],
  },
  {
    version: '2.1.1',
    date: '2026-09-27',
    time: '10:00',
    title: 'Configurações reorganizadas e interruptor do apoio ao vivo',
    changes: [
      'Nova página de Configurações com menu lateral por temas: Geral, Tickets, Comunicação, Acesso e Conteúdos. Cada secção tem um título, uma explicação e blocos separados, e o endereço guarda a secção aberta.',
      'Apoio ao vivo: interruptor "Ligar/Desligar" em destaque, que grava na hora. Vem desligado; enquanto estiver desligado ninguém vê o balão, a faixa nem a entrada no menu.',
      'O menu das Configurações indica se o apoio ao vivo, o Teams e o modo demo estão ligados.',
      'Retirados campos que não tinham efeito (URL base, fuso horário, duração da sessão, formulário de Active Directory e servidor SMTP): estas definições estão no ficheiro app.env do servidor, o que agora é explicado na página.',
      'Na página Chat, quem atende o apoio é avisado quando o apoio ao vivo está desligado.',
    ],
  },
  {
    version: '2.1.0',
    date: '2026-09-25',
    time: '18:00',
    title: 'Microsoft Teams, apoio ao vivo mais visível e "Ver como docente"',
    changes: [
      'Avisos num canal do Microsoft Teams (Configurações → Microsoft Teams): novo ticket, apoio ao vivo à espera (com botão "Atender"), ticket fora do prazo e resposta de quem fez o pedido. Configura-se com um fluxo de trabalho do Teams, sem administrador nem acesso externo ao servidor.',
      'Apoio ao vivo mais fácil de encontrar: faixa no Painel inicial ("Apoio ao vivo disponível agora… até às 17h" ou quando abre), entrada "Apoio ao vivo" no menu com indicação Online/Fechado, sugestão na página Novo ticket e balão de apresentação na primeira visita.',
      'Novo interruptor "Ver como docente" no topo (técnicos, Direção e administradores): a aplicação passa a mostrar exatamente o menu, as páginas e os tickets que um docente vê, sem notas internas, com uma faixa para voltar à vista normal.',
      'O endereço do Teams nunca é enviado a quem não é administrador.',
    ],
  },
  {
    version: '2.0.0',
    date: '2026-09-25',
    time: '17:00',
    title: 'Tempo real: tickets ao vivo, chat da equipa e apoio ao vivo',
    changes: [
      'Tickets ao vivo: novas respostas, mudanças de estado e atribuições aparecem sem recarregar a página; vê-se quem está a ver o ticket e quem está a escrever ("Maria Serra está a escrever…"). Os contadores do menu atualizam-se sozinhos.',
      'Chat da equipa (menu Chat): conversas diretas e grupos, com grupos automáticos por papel (ex.: Equipa TIC, Direção), mensagens não lidas, "visto", "a escrever…", referências a tickets (T-123) e notificação no telemóvel quando não se está na aplicação.',
      'Apoio ao vivo: balão de chat no canto do ecrã para os docentes. Os técnicos ligam "Disponível para apoio", aceitam o pedido e respondem em tempo real; a conversa pode ser convertida em ticket.',
      'Horário do apoio ao vivo: segunda e quarta 14h–17h; terça, quinta e sexta 10h–13h. Fora do horário, ou se ninguém aceitar em 5 minutos, a mensagem passa automaticamente a ticket.',
      'Novas permissões em Papéis e permissões: "Usar o chat da equipa" e "Responder ao apoio ao vivo". Novo separador Configurações → Chat e apoio ao vivo (horário, tempo de espera e estado da ligação em tempo real).',
      'Se a rede ou um proxy bloquear WebSockets, a aplicação passa sozinha a um modo compatível que atualiza de poucos em poucos segundos.',
      'As mensagens privadas e as notas internas continuam protegidas: os avisos em tempo real nunca levam conteúdo, só pedem ao navegador para recarregar o que cada pessoa já pode ver.',
    ],
  },
  {
    version: '1.9.10',
    date: '2026-09-25',
    time: '15:30',
    title: 'Papel correto na lista de destinatários das mensagens privadas',
    changes: [
      'Na escolha do destinatário de uma mensagem privada aparece agora o papel atribuído a cada pessoa (ex.: "Equipa TIC", "Direção"), em vez de "técnico" para todos.',
    ],
  },
  {
    version: '1.9.9',
    date: '2026-09-25',
    time: '15:00',
    title: 'Papéis e permissões editáveis (Direção e Equipa TIC)',
    changes: [
      'Novo separador "Papéis e permissões" em Utilizadores: editar o nome, ícone, cor e permissões de cada papel, e criar papéis novos.',
      'Novos papéis "Direção" (vê todos os tickets e as estatísticas, só de leitura) e "Equipa TIC" (gere tickets, vê estatísticas e edita a base de conhecimento).',
      'Permissões disponíveis: ver todos os tickets, gerir tickets, ver estatísticas, editar a base de conhecimento, gerir utilizadores e papéis, configurações do sistema.',
      'As permissões são verificadas no servidor; o menu e as páginas mostram só o que cada papel pode usar. O Administrador tem sempre todas as permissões.',
      'Na lista de utilizadores, o seletor de papel inclui os papéis novos; atribuir um papel manualmente bloqueia a sincronização com o Entra ID para esse utilizador.',
      'Quem só pode consultar vê os tickets em modo de leitura, sem caixa de resposta nem controlos de edição.',
      'Corrigido: na Gestão de tickets a coluna Solicitante ficava desalinhada para técnicos; nomes reduzidos com o grupo de recrutamento.',
    ],
  },
  {
    version: '1.9.8',
    date: '2026-09-25',
    time: '14:00',
    title: 'Nomes reduzidos com grupo de recrutamento, escola na lista e notas internas protegidas',
    changes: [
      'Nomes reduzidos na conversa, em "Aberto por" e nos detalhes (ex.: "Maria Serra"), com o grupo de recrutamento e a sua abreviatura (ex.: "510 FQ"); o nome completo aparece ao passar o rato.',
      'Nova coluna "Escola" na lista "Os meus tickets", e o grupo de recrutamento junto ao solicitante.',
      'As notas internas passam a ser enviadas pelo servidor apenas a técnicos e administradores — quem abriu o pedido deixa de as poder ver.',
      'Editar ou apagar uma nota interna já não aparece no histórico público do ticket.',
      'Corrigida a cor da etiqueta da escola no modo claro.',
    ],
  },
  {
    version: '1.9.7',
    date: '2026-09-25',
    time: '13:30',
    title: 'Responder e alterar o estado num só clique',
    changes: [
      'Novo seletor de estado junto ao botão Enviar (técnicos e administradores): escolha, por exemplo, "Resolvido" e o botão passa a "Enviar e marcar Resolvido".',
      'Por omissão fica "Manter estado"; depois de enviar volta a "Manter estado".',
      'A resposta rápida "Resolvido ✓" pré-seleciona o estado Fechado, que pode ser alterado antes de enviar.',
    ],
  },
  {
    version: '1.9.6',
    date: '2026-09-25',
    time: '13:00',
    title: 'Escola em destaque no topo do ticket',
    changes: [
      'O nome da escola aparece agora no topo de cada ticket, junto ao estado e à prioridade, num destaque azul-turquesa — sem ser preciso procurar nos detalhes.',
    ],
  },
  {
    version: '1.9.5',
    date: '2026-09-25',
    time: '12:30',
    title: 'Mensagens privadas agrupadas num bloco',
    changes: [
      'Mensagens privadas seguidas entre as mesmas duas pessoas aparecem agora juntas dentro de um único bloco violeta, recuado da conversa pública.',
      'O bloco tem um cabeçalho "Conversa privada · você e …" com o botão "Responder em privado".',
      'Conversas privadas com pessoas diferentes ficam em blocos separados.',
    ],
  },
  {
    version: '1.9.4',
    date: '2026-09-25',
    time: '12:00',
    title: 'Mensagens privadas destacadas na conversa',
    changes: [
      'As mensagens privadas têm agora uma cor de fundo própria (violeta), com uma barra lateral, diferente das respostas públicas e das notas internas.',
      'Aparecem ligeiramente recuadas para a direita, separadas do fluxo normal da conversa.',
    ],
  },
  {
    version: '1.9.3',
    date: '2026-09-25',
    time: '11:30',
    title: 'Mensagens privadas para mais pessoas',
    changes: [
      'As mensagens privadas podem ser enviadas a qualquer técnico ou administrador, mesmo que o ticket ainda não esteja atribuído.',
      'Também é possível escrever em privado ao solicitante, aos responsáveis e aos seguidores do ticket.',
      'A lista de destinatários está agrupada em "Neste ticket" e "Técnicos e administradores", com nomes reduzidos.',
      'Corrigido: em tickets sem técnico atribuído a opção "Mensagem privada" não aparecia.',
    ],
  },
  {
    version: '1.9.2',
    date: '2026-09-25',
    time: '11:00',
    title: 'Lista "Os meus tickets" arrumada',
    changes: [
      'O solicitante aparece com o nome reduzido (primeiro e último nome); o nome completo surge ao passar o rato.',
      'Corrigida a formatação das linhas da tabela (coluna Estado desalinhada e tabela a sair do ecrã).',
      'O assunto tem mais espaço e as categorias compridas são encurtadas.',
    ],
  },
  {
    version: '1.9.1',
    date: '2026-09-25',
    time: '10:30',
    title: '"Os meus tickets" com solicitante, categoria e indicação de lembrete',
    changes: [
      'Retiradas as colunas "Tempo de resposta", "Emails" e "Atualizado" da lista "Os meus tickets".',
      'Novas colunas "Solicitante" (quem fez o pedido) e "Categoria".',
      'Ícone de despertador a seguir ao ID quando tem um lembrete seu por enviar nesse ticket (só você o vê).',
      'As notificações por email do autor continuam a poder ser ligadas ou desligadas dentro do ticket.',
    ],
  },
  {
    version: '1.9.0',
    date: '2026-09-25',
    time: '10:00',
    title: 'Mensagens privadas dentro do ticket',
    changes: [
      'Nova opção "Mensagem privada" na caixa de resposta: escolha a pessoa atribuída ao ticket e só ela e você veem a mensagem.',
      'O solicitante, os seguidores, os outros técnicos e os administradores não veem as mensagens privadas — a filtragem é feita no servidor.',
      'Quem recebe uma mensagem privada pode clicar em "Responder em privado" para continuar a conversa só entre os dois.',
      'O destinatário recebe email e notificação só para si; se responder ao email, a resposta fica também privada.',
      'Mensagens privadas não geram eventos no histórico, não são reenviadas à empresa de apoio e só o autor as pode editar ou apagar.',
    ],
  },
  {
    version: '1.8.9',
    date: '2026-09-24',
    time: '17:00',
    title: '"Lembrar-me deste ticket" sempre disponível ao responder',
    changes: [
      'A opção "Lembrar-me deste ticket" passa a estar sempre visível na caixa de resposta, com um interruptor para ativar ou desativar — já não depende de "Nota interna".',
      'Disponível para administradores, técnicos e docentes a quem o ticket está atribuído.',
      'O lembrete é sempre privado: mesmo numa resposta pública, só quem o criou vê a indicação do lembrete e recebe o aviso.',
    ],
  },
  {
    version: '1.8.8',
    date: '2026-09-24',
    time: '16:00',
    title: 'Lembretes nas notas internas',
    changes: [
      'Ao escrever uma nota interna num ticket, técnicos e administradores podem escolher um dia e hora para serem lembrados (atalhos "Amanhã", "Daqui a 3 dias" e "Próxima segunda"; fins de semana são saltados).',
      'Na data escolhida, o autor da nota recebe um email e uma notificação no telemóvel com o texto da nota e a ligação para o ticket. O lembrete é só para quem o criou.',
      'A nota mostra "Lembrete dd/mm às hh:mm" até ser enviado, e depois "Lembrete enviado". Apagar a nota cancela o lembrete.',
    ],
  },
  {
    version: '1.8.7',
    date: '2026-09-24',
    time: '12:30',
    title: 'Cartões do Painel numa só linha',
    changes: [
      'Os cartões de números do Painel inicial (Abertos, Em curso, Resolvidos e, para técnicos, A expirar e Fora do prazo) ficam todos numa só linha, em blocos mais pequenos.',
      'No telemóvel a linha desliza para o lado; a descrição de cada cartão aparece ao passar o rato por cima.',
    ],
  },
  {
    version: '1.8.6',
    date: '2026-09-24',
    time: '11:30',
    title: 'Painel: "A expirar" e "Fora do prazo" para técnicos',
    changes: [
      'Retirado o cartão "Tempo médio até resolução" do Painel inicial.',
      'Técnicos e administradores veem dois cartões novos: "A expirar" (menos de 25% do tempo de resposta restante) e "Fora do prazo" (tempo de resposta ultrapassado). Ao clicar, abrem a lista desses tickets.',
      'Os prazos seguem a mesma regra dos selos de tempo de resposta: prazos que calham ao fim de semana passam para segunda-feira às 9h.',
      'Em "Os meus tickets", técnicos e administradores têm os filtros "A expirar" e "Fora do prazo".',
    ],
  },
  {
    version: '1.8.5',
    date: '2026-09-24',
    time: '10:30',
    title: 'Página "Sobre" atualizada',
    changes: [
      'A página "Sobre" descreve agora o desenvolvimento feito com o Claude Code (Anthropic), o fluxo de trabalho atual (do pedido ao teste, preview e publicação) e o que foi construído.',
      'Novos números do projeto: versões publicadas, commits e linhas de código. A referência ao ChatGPT fica reduzida ao uso pontual que teve.',
    ],
  },
  {
    version: '1.8.4',
    date: '2026-09-24',
    time: '10:00',
    title: 'Formulário "Não tenho acesso ao mail institucional" com email e telefone',
    changes: [
      'O formulário passa a pedir um email para resposta (obrigatório, pode ser pessoal) e um contacto telefónico (opcional).',
      'O email recebido mostra o email e o telefone, e responder a esse email envia a resposta diretamente para a pessoa.',
    ],
  },
  {
    version: '1.8.3',
    date: '2026-09-22',
    time: '23:30',
    title: 'Categorias à escolha, cartões clicáveis, conteúdo demo escondido e edição de artigos',
    changes: [
      'Painel inicial: os cartões Abertos, Em curso e Resolvidos passam a ser clicáveis e abrem "Os meus tickets" já filtrados.',
      'Novo botão "Categorias" no Painel inicial e em "Os meus tickets": cada utilizador escolhe que categorias quer ver (ex.: esconder Inovar). A escolha fica guardada na conta.',
      'Tickets e comentários feitos em modo demo ficam escondidos dos utilizadores reais e não enviam emails nem notificações. Pode ser alterado em Configurações → Geral → "Mostrar tickets e mensagens do modo demo".',
      'Base de conhecimento: os administradores já podem editar artigos, tanto na página da Base de conhecimento como em Configurações → Base de conhecimento.',
    ],
  },
  {
    version: '1.8.2',
    date: '2026-09-22',
    time: '22:30',
    title: 'Todos entram pelo Painel inicial + botões do login harmonizados',
    changes: [
      'Depois de iniciar sessão, todos os utilizadores (incluindo técnicos e administradores) vão para o Painel inicial.',
      'Ecrã de login: o botão "Entrar com email ou conta da escola" passa a usar o azul da própria aplicação, e "Não tenho acesso ao mail institucional" passa a um estilo suave a condizer, em vez de verde.',
    ],
  },
  {
    version: '1.8.1',
    date: '2026-09-22',
    time: '22:00',
    title: 'Modo demo configurável + login mais coerente',
    changes: [
      'O modo demo volta a existir, mas desligado por omissão: ativa-se em Configurações → Geral → Funcionalidades → "Modo demo".',
      'É possível escolher que perfis ficam disponíveis em demo (Docente, Técnico, Administrador). Por omissão só Docente.',
      'Ao desligar o modo demo, as sessões demo abertas deixam de funcionar de imediato.',
      'Quem está em modo demo vê um aviso no topo com o botão "Sair do modo demo".',
      'Ecrã de login (design Moderno): o painel da direita passa a tons claros e suaves, coerente com o resto da página, em vez do azul forte.',
    ],
  },
  {
    version: '1.8.0',
    date: '2026-09-22',
    time: '21:00',
    title: 'Novo design do Painel inicial e do ecrã de login',
    changes: [
      'Painel inicial redesenhado: banner de boas-vindas com saudação e data, estatísticas em cartões coloridos, tickets recentes com a cor do estado e atalhos de categoria em mosaicos.',
      'Ecrã de login redesenhado no mesmo estilo, com painel informativo colorido e botões mais visíveis.',
      'Os atalhos "Novo pedido rápido" abrem o formulário já com a categoria escolhida.',
      'Novo: em Configurações → Geral → Funcionalidades é possível voltar ao design anterior ("Clássico") ou manter o novo ("Moderno"). A escolha aplica-se a todos os utilizadores.',
    ],
  },
  {
    version: '1.7.99',
    date: '2026-09-22',
    time: '14:30',
    title: 'Botão de contacto com estilo próprio',
    changes: [
      'O botão "Não tenho acesso ao mail institucional" no ecrã de login passou de link de texto a botão sólido (cor diferente das restantes ações, mais pequeno que "Entrar com email ou conta da escola").',
    ],
  },
  {
    version: '1.7.98',
    date: '2026-09-22',
    time: '14:00',
    title: 'Contacto para quem não tem acesso ao mail institucional',
    changes: [
      'Novo botão "Não tenho acesso ao mail institucional" no ecrã de login, que abre um formulário a pedir nome, grupo de recrutamento, escola e mensagem.',
      'Ao submeter, é enviado um email para o endereço configurado em Administração → Configurações → Geral → "Contacto Sem acesso ao mail institucional" (por omissão: helpdesk_aeeq@queiroz.pt).',
      'Não é necessária sessão iniciada — o formulário funciona mesmo sem acesso a qualquer conta.',
    ],
  },
  {
    version: '1.7.97',
    date: '2026-09-22',
    time: '13:00',
    title: 'Interruptores invisíveis corrigidos + emails condensados',
    changes: [
      'Corrigido: os interruptores (on/off) de "Avisos de categoria", "Aviso no ecrã de login", Active Directory, notificações automáticas e ativar/desativar utilizador estavam invisíveis (não tinham estilo aplicado) — apareciam clicáveis mas sem indicação visual do estado.',
      'Novo: várias atualizações seguidas ao mesmo ticket (ex: comentário + resolver + fechar em poucos minutos) juntam-se agora num único email condensado por destinatário, em vez de um email por cada alteração.',
      'Configurável via MAIL_DIGEST_WINDOW_SECONDS no servidor (120s por omissão; 0 desativa o agrupamento).',
    ],
  },
  {
    version: '1.7.96',
    date: '2026-09-22',
    time: '12:00',
    title: 'Erro visível ao gravar o aviso de login',
    changes: [
      'Se o interruptor ou o texto do "Aviso no ecrã de login" não gravarem (ex: servidor ainda não atualizado), aparece agora uma mensagem de erro em Configurações → Geral em vez de falhar silenciosamente.',
    ],
  },
  {
    version: '1.7.95',
    date: '2026-09-22',
    time: '11:00',
    title: 'Aviso configurável no ecrã de login',
    changes: [
      'Nova janela de aviso no ecrã de login, configurável em Administração → Configurações → Geral ("Aviso no ecrã de login").',
      'Pode ser ativada/desativada e o texto pode ser editado a qualquer momento; por omissão vem preenchida com o aviso de uso exclusivo para docentes e não docentes, com contacto helpdesk_aeeq@queiroz.pt.',
    ],
  },
  {
    version: '1.7.94',
    date: '2026-09-22',
    time: '10:00',
    title: 'Remoção do modo demo',
    changes: [
      'Removido o "Entrar em modo demo" do ecrã de login (botão, seletor de perfil e endpoint /auth/demo-login).',
      'Removido o aviso persistente de "modo de demonstração" que aparecia no topo das páginas.',
      'Guias de instalação atualizados: o primeiro administrador entra agora via LDAP (LDAP_ADMIN_GROUP) ou Azure AD (AZURE_ADMIN_EMAILS), ou por conta local criada diretamente na base de dados para ambientes de desenvolvimento sem AD configurado.',
    ],
  },
  {
    version: '1.7.93',
    date: '2026-06-12',
    time: '11:00',
    title: 'Fecho automático por inatividade',
    changes: [
      'Tickets sem resposta há 7 dias recebem um aviso automático (email + entrada no histórico) indicando que serão fechados em 2 dias se não houver resposta.',
      'Se continuar sem resposta 2 dias após o aviso, o ticket é fechado automaticamente.',
      'Se o utilizador responder após o aviso, o temporizador reinicia — o ticket não é fechado.',
      'A verificação corre automaticamente a cada 6 horas. Também disponível manualmente em Gestão de tickets → "Verificar inatividade".',
    ],
  },
  {
    version: '1.7.92',
    date: '2026-06-11',
    time: '12:30',
    title: 'Destaque verde nas listas de tickets fechados via email',
    changes: [
      'Os tickets fechados/resolvidos automaticamente por email aparecem agora com fundo verde claro também na "Gestão de tickets" e em "Os meus tickets" (tabela e cartões móveis).',
      'Novo campo no ticket que regista o fecho automático via email, com migração que marca retroativamente os tickets já fechados desta forma.',
      'Ao passar o rato sobre a linha aparece a indicação "Fechado automaticamente via email".',
    ],
  },
  {
    version: '1.7.91',
    date: '2026-06-11',
    time: '11:45',
    title: 'Menu lateral compacto em ecrãs baixos',
    changes: [
      'Corrigido: em ecrãs com pouca altura (ou zoom elevado), os últimos itens do menu de administração (Sugestões, Categorias, Configurações, Backup, Log de emails) ficavam escondidos sem indicação visual.',
      'O menu compacta-se automaticamente quando a janela é baixa, e a barra de scroll do menu passa a ser visível.',
    ],
  },
  {
    version: '1.7.90',
    date: '2026-06-11',
    time: '11:00',
    title: 'Destaque visual no log de emails',
    changes: [
      'No log de emails, as linhas de tickets fechados/resolvidos automaticamente aparecem agora com fundo verde claro.',
      'Corrigido: o destaque não aparecia porque usava uma cor inexistente no tema.',
      'Sincronização de emails: timeout aumentado para 120s — a mensagem de sucesso já não é cortada a meio do processamento.',
    ],
  },
  {
    version: '1.7.89',
    date: '2026-06-09',
    time: '10:00',
    title: 'Log de emails na app',
    changes: [
      'Nova página "Log de emails" no painel de administração — mostra os últimos 200 eventos gerados pelo processamento de emails (respostas recebidas e tickets fechados automaticamente).',
      'Visível em Administração → Log de emails (apenas para administradores).',
    ],
  },
  {
    version: '1.7.88',
    date: '2026-05-26',
    time: '23:10',
    title: 'Fecho automático de tickets por email',
    changes: [
      'Quando a caixa de correio recebe um email com "FECHADO" ou "resolvido" no assunto e o corpo contém "O Seu Ticket de Apoio ao Cliente [Ticket #XX]", o ticket é automaticamente fechado/resolvido.',
      'Funciona com remetentes externos (empresa de apoio) sem necessidade de conta no helpdesk.',
      'Novo botão "Fechar tickets por email" na gestão de tickets — processa todos os emails da caixa (incluindo já lidos) para fechar tickets mais antigos.',
      'A sincronização automática periódica também deteta estes emails e fecha os tickets em tempo real.',
    ],
  },
  {
    version: '1.7.87',
    date: '2026-05-26',
    time: '22:34',
    title: 'Botões empresa de apoio com texto visível',
    changes: [
      'Botão de envio à empresa de apoio no cabeçalho do ticket passa a mostrar texto ("Enviar para empresa de apoio" / "Reenviar à empresa de apoio") em vez de apenas ícone.',
      'Botão por comentário renomeado de "Reenviar" para "Enviar para empresa de apoio".',
    ],
  },
  {
    version: '1.7.86',
    date: '2026-05-26',
    time: '15:56',
    title: 'Botão "Reenviar" por comentário + reversão de resolução empresa de apoio',
    changes: [
      'Botão "Reenviar" adicionado em cada comentário (ao lado de Editar/Apagar) — permite enviar aquela resposta específica à empresa de apoio com um clique.',
      'Novo botão "Reverter" no cabeçalho do ticket quando marcado como "Resolvido pela empresa de apoio" — permite desfazer a marcação se a situação não estiver realmente resolvida.',
      'Corrigido: o estado "escalado/resolvido pela empresa de apoio" era calculado incorretamente — agora usa o campo real do ticket em vez do histório de eventos.',
    ],
  },
  {
    version: '1.7.85',
    date: '2026-05-26',
    time: '15:15',
    title: 'Atualizações automáticas à empresa de apoio + botão reenviar',
    changes: [
      'Quando um ticket já reportado à empresa de apoio recebe um novo comentário público, o email é automaticamente reenviado à empresa com o conteúdo do comentário.',
      'Qualquer alteração ao ticket (estado, prioridade, conteúdo) também notifica automaticamente a empresa de apoio.',
      'Novo botão de envio/reenvio rápido no cabeçalho do ticket (ícone de email) para staff — distingue entre reportar pela primeira vez e reenviar.',
    ],
  },
  {
    version: '1.7.84',
    date: '2026-05-20',
    time: '11:42',
    title: 'Correção de layout em tablets e iPads — todos os menus',
    changes: [
      'Removido o banner azul de título (page-hero) de todos os menus — era duplicado do título já visível no cabeçalho.',
      'Cabeçalho mobile mostra agora o nome da página atual em vez do nome do agrupamento.',
      'Grelha de 4 colunas (estatísticas) passa para 2 colunas em ecrãs com menos de 1100px para evitar cartões esmagados com a barra lateral visível.',
      'Gráficos das Estatísticas passam para coluna única em ecrãs estreitos (≤1099px).',
    ],
  },
  {
    version: '1.7.83',
    date: '2026-05-20',
    time: '11:29',
    title: 'Remoção de títulos duplicados em todos os menus',
    changes: [
      'Removidos os títulos (h1) de todas as páginas que já recebem o cabeçalho compacto do layout — elimina a duplicação visual.',
      'Botões de ação e contagens mantidos nas respetivas páginas.',
    ],
  },
  {
    version: '1.7.82',
    date: '2026-05-20',
    time: '11:16',
    title: 'Correção de layout no iPad',
    changes: [
      'Título do cabeçalho já não parte em duas linhas em ecrãs médios — truncado com reticências se necessário.',
      'Dashboard no iPad: tabela de tickets e estatísticas em 4 colunas a partir de 820px; painel de categorias só aparece ao lado em ecrãs largos (≥1150px), evitando a tabela espremida.',
    ],
  },
  {
    version: '1.7.81',
    date: '2026-05-19',
    time: '11:14',
    title: 'Cabeçalho compacto em todos os menus; tickets concluídos escondidos',
    changes: [
      'Todos os menus têm agora um cabeçalho azul compacto com ícone e título — design consistente em toda a app.',
      'As páginas "Sobre" e "Versão / Atualizações" deixaram de ter um hero gigante — usam o cabeçalho comum do layout.',
      'Na lista "Os meus tickets", os tickets resolvidos e fechados ficam escondidos por defeito. Um botão no final permite mostrá-los.',
    ],
  },
  {
    version: '1.7.80',
    date: '2026-05-19',
    time: '08:38',
    title: 'Página "Sobre" sem historial de versões duplicado',
    changes: [
      'O historial de versões foi removido da página "Sobre" — já existe na página dedicada "Versão / Atualizações". A página "Sobre" foca-se agora exclusivamente na autoria, método de criação, tecnologias e direitos de autor.',
    ],
  },
  {
    version: '1.7.79',
    date: '2026-05-19',
    time: '00:13',
    title: 'Página "Sobre" restaurada com todo o conteúdo',
    changes: [
      'Restaurado o conteúdo completo da página "Sobre": autoria, método de criação com IA (Claude Code + ChatGPT), fluxo de trabalho, citação, tecnologias e direitos de autor.',
      'Novo design: hero banner azul degradê + secções em cards + timeline de versões Quasar integrada.',
    ],
  },
  {
    version: '1.7.78',
    date: '2026-05-19',
    time: '00:08',
    title: 'Correção: página "Sobre" vazia; redesign "Versão / Atualizações"',
    changes: [
      'Corrigida a página "Sobre" que aparecia em branco — causado por <q-page> fora de um q-layout Quasar.',
      'A página "Versão / Atualizações" foi redesenhada com o mesmo estilo: hero banner azul, timeline colorida e botão "Mostrar versões anteriores".',
    ],
  },
  {
    version: '1.7.77',
    date: '2026-05-19',
    time: '00:02',
    title: 'Página "Sobre" com historial de versões dinâmico',
    changes: [
      'A página "Sobre" passa a gerar o historial de versões automaticamente a partir dos dados internos da app — versão, data, hora e notas de cada atualização.',
      'As primeiras 10 versões são mostradas por defeito; botão "Mostrar versões anteriores" expande o historial completo.',
      'Versão atual refletida no hero banner automaticamente.',
    ],
  },
  {
    version: '1.7.76',
    date: '2026-05-18',
    time: '22:01',
    title: 'Página "Sobre" redesenhada',
    changes: [
      'Nova página "Sobre" com hero banner, historial de versões em timeline e grelha de tecnologias — usando componentes Quasar nativos.',
    ],
  },
  {
    version: '1.7.75',
    date: '2026-05-18',
    time: '19:01',
    title: 'Painel: tempo médio de resolução calculado',
    changes: [
      'O card "Tempo Médio" calcula agora o tempo médio entre a criação e a resolução dos tickets concluídos (resolvidos ou fechados). Apresentado em horas (ex: 4h) ou dias e horas (ex: 2d 6h). Mostra "—" se não existirem tickets concluídos.',
    ],
  },
  {
    version: '1.7.74',
    date: '2026-05-18',
    time: '18:53',
    title: 'Painel: contagem de resolvidos inclui tickets fechados',
    changes: [
      'O card "Resolvidos" no painel inicial passa a contar tickets com estado "Resolvido" e "Fechado" — ambos representam pedidos concluídos.',
    ],
  },
  {
    version: '1.7.73',
    date: '2026-05-18',
    time: '17:27',
    title: 'Gestão de tickets: badge e filtro "Empresa de apoio"',
    changes: [
      'Adicionado filtro "Reportados à empresa de apoio" na página de gestão de tickets.',
      'Badge laranja "E" agora visível também na vista de telemóvel.',
      'Backend: suporte ao parâmetro is_escalated no endpoint de listagem admin.',
    ],
  },
  {
    version: '1.7.72',
    date: '2026-05-18',
    time: '17:19',
    title: 'Correção: cabeçalho e descrição do ticket no telemóvel',
    changes: [
      'Cabeçalho do ticket restruturado: no telemóvel o título aparece por cima e os badges (estado, prioridade) aparecem por baixo — elimina o layout partido com texto espalhado por toda a página.',
      'Descrição e comentários: linhas em branco excessivas (3 ou mais seguidas) são colapsadas numa única, evitando espaços gigantes no texto.',
    ],
  },
  {
    version: '1.7.71',
    date: '2026-05-18',
    time: '09:18',
    title: '"Fornecedor" renomeado para "Empresa de apoio informático"',
    changes: [
      '"Fornecedor" passa a chamar-se "Empresa de apoio informático" em toda a interface.',
      '"Escalar" passa a chamar-se "Reportar" — ex: "Reportar à empresa de apoio".',
    ],
  },
  {
    version: '1.7.70',
    date: '2026-05-18',
    time: '07:43',
    title: 'Dashboard adaptado para dispositivos móveis',
    changes: [
      'No telemóvel, os tickets recentes deixam de aparecer numa tabela cortada e passam a mostrar uma lista de cartões com título, estado, prioridade e data.',
      'A coluna de categorias aparece abaixo dos tickets (em vez de ao lado) com um botão "Novo pedido" destacado.',
      'Os cartões de estatísticas mantêm a grelha 2×2 no telemóvel e passam a 4×1 no computador.',
      'No computador, o layout original com tabela e coluna lateral é mantido.',
    ],
  },
  {
    version: '1.7.69',
    date: '2026-05-17',
    time: '18:40',
    title: 'Correção: popup de aviso de categoria não aparecia',
    changes: [
      'Corrigido: o popup de aviso não aparecia quando o aviso estava ativo mas o texto ainda não tinha sido configurado.',
      'Ao clicar "Aviso ativo" numa categoria sem texto definido, o diálogo de edição abre automaticamente para configurar o texto.',
      'Na criação de ticket, se o aviso estiver ativo mas sem texto, mostra uma mensagem genérica em vez de não mostrar nada.',
    ],
  },
  {
    version: '1.7.68',
    date: '2026-05-17',
    time: '18:34',
    title: 'Link "Categorias" no menu lateral de administração',
    changes: [
      'Adicionado item "Categorias" no menu lateral de administração — permite aceder diretamente à página de gestão de categorias (ícones, cores, avisos).',
    ],
  },
  {
    version: '1.7.67',
    date: '2026-05-17',
    time: '17:40',
    title: 'Aviso de categoria ativável diretamente no cartão',
    changes: [
      'Cada categoria tem agora um botão "Aviso ativo / Aviso inativo" no próprio cartão — clique para ativar ou desativar o aviso sem entrar no diálogo de edição.',
    ],
  },
  {
    version: '1.7.66',
    date: '2026-05-17',
    time: '15:56',
    title: 'Ícones coloridos, avisos de categoria e anexos nas respostas',
    changes: [
      'Categorias com ícone colorido configurável — a cor e o ícone (Material Icons) são agora editáveis em Administração → Categorias.',
      'Aviso ao selecionar categoria: cada categoria pode ter um texto de aviso configurável que aparece numa janela "Atenção" ao criar um ticket.',
      'Ativar/desativar avisos de categoria globalmente em Configurações → Geral.',
      'Novo botão "Anexar" na caixa de resposta de um ticket — permite juntar imagens ou ficheiros às respostas, tal como na criação de tickets.',
    ],
  },
  {
    version: '1.7.65',
    date: '2026-05-15',
    time: '12:43',
    title: 'Atribuição aleatória de responsável ao escolher grupo',
    changes: [
      'Ao atribuir um grupo a um ticket, um membro é automaticamente escolhido de forma aleatória como responsável',
      'Removido separador de Manutenção das Configurações',
    ],
  },
  {
    version: '1.7.63',
    date: '2026-05-14',
    time: '23:26',
    title: 'Botão de manutenção para fechar tickets resolvidos',
    changes: ['Configurações → Manutenção: botão "Executar correção" fecha todos os tickets com resposta "A situação foi resolvida…" que ainda estavam abertos'],
  },
  {
    version: '1.7.62',
    date: '2026-05-14',
    time: '23:20',
    title: 'Endpoint de correção manual de tickets resolvidos',
    changes: ['Adicionado endpoint admin POST /api/v1/admin/fix-resolved-tickets para fechar manualmente tickets com resposta "Resolvido ✓"'],
  },
  {
    version: '1.7.61',
    date: '2026-05-14',
    time: '23:18',
    title: 'Correção: migração retroativa de tickets resolvidos',
    changes: ['Corrigida pesquisa da mensagem "Resolvido ✓" para fechar tickets anteriores independentemente de codificação do texto'],
  },
  {
    version: '1.7.60',
    date: '2026-05-14',
    time: '23:05',
    title: 'Migração retroativa: tickets com "Resolvido ✓" fechados',
    changes: ['Tickets onde a resposta "Resolvido ✓" foi usada anteriormente são agora fechados automaticamente na próxima reinicialização'],
  },
  {
    version: '1.7.59',
    date: '2026-05-14',
    time: '22:53',
    title: 'Página de sugestões visível na área de administração',
    changes: ['Administradores podem consultar todas as sugestões enviadas em "Administração → Sugestões"'],
  },
  {
    version: '1.7.58',
    date: '2026-05-14',
    time: '22:48',
    title: 'Resposta "Resolvido ✓" fecha o ticket automaticamente',
    changes: [
      'Quando um técnico ou administrador usa o botão "Resolvido ✓" para responder, o ticket é automaticamente fechado ao enviar.',
      'O botão fica verde quando selecionado para indicar que o ticket será fechado com o envio.',
      'Todos os tickets que já estavam em estado "Resolvido" foram automaticamente fechados no arranque.',
    ],
  },
  {
    version: '1.7.57',
    date: '2026-05-14',
    time: '13:14',
    title: 'Direitos de autor e propriedade intelectual',
    changes: [
      'Adicionada secção "Direitos de autor" na página Sobre com a declaração de propriedade exclusiva e proibição de utilização não autorizada.',
      'Criado ficheiro LICENSE no repositório GitHub com aviso completo em português e inglês.',
    ],
  },
  {
    version: '1.7.56',
    date: '2026-05-14',
    time: '11:27',
    title: 'Badge "F" laranja para tickets escalados ao fornecedor',
    changes: [
      'Nas listas de tickets, os tickets escalados para o fornecedor externo passam a mostrar um círculo laranja "F" ao lado do estado.',
      'O indicador é visível tanto em "Os meus tickets" como em "Gestão de tickets".',
    ],
  },
  {
    version: '1.7.53',
    date: '2026-05-14',
    time: '11:09',
    title: 'Indicador "Fornecedor" nas listas de tickets',
    changes: [
      'Nas listas "Os meus tickets" e "Gestão de tickets", os tickets escalados para o fornecedor externo passam a mostrar uma etiqueta laranja "Fornecedor" ao lado do estado.',
      'A etiqueta desaparece automaticamente quando o técnico regista que o fornecedor resolveu o problema.',
    ],
  },
  {
    version: '1.7.52',
    date: '2026-05-14',
    time: '09:26',
    title: 'Estados e prioridades traduzidos nos emails',
    changes: [
      'Os emails de atualização de ticket passam a mostrar o estado e a prioridade em português: Aberto, Em Curso, A aguardar utilizador, Resolvido, Fechado; Baixa, Média, Alta, Urgente.',
    ],
  },
  {
    version: '1.7.51',
    date: '2026-05-14',
    time: '09:11',
    title: 'Destinatários de sugestões configuráveis',
    changes: [
      'Nas Configurações → Notificações, o administrador pode agora definir os emails que recebem uma notificação quando é enviada uma nova sugestão.',
      'O email de notificação inclui o nome do autor, a data e o texto da sugestão.',
    ],
  },
  {
    version: '1.7.50',
    date: '2026-05-14',
    time: '09:02',
    title: 'Sugestões, traduções e limpeza de atualizações',
    changes: [
      'Novo menu "Sugestões" no painel lateral — qualquer utilizador autenticado pode enviar ideias ou sugestões de melhoria da aplicação.',
      'Os eventos dos tickets passam a mostrar os estados e prioridades em português: Aberto, Atribuído, Em Curso, A aguardar utilizador, Resolvido, Fechado; Baixa, Média, Alta, Urgente.',
      'Histórico de atualizações: removidas entradas sobre notificações push que não estavam a funcionar de forma fiável.',
    ],
  },
  {
    version: '1.7.49',
    date: '2026-05-13',
    time: '09:47',
    title: 'Emails silenciados',
    changes: [
      'Corrigido um problema onde autores que desativavam "Atualizações por e-mail" continuavam a recebê-las se pertencessem a uma equipa ou grupo designado para resolver esse pedido.',
    ],
  },
  {
    version: '1.7.48',
    date: '2026-05-13',
    time: '09:35',
    title: 'Usabilidade móvel',
    changes: [
      'A barra de navegação (separadores) no telemóvel permite agora deslizar suavemente com o dedo de forma muito fluida, e as barras de scroll foram escondidas para um aspeto mais limpo.',
    ],
  },
  {
    version: '1.7.47',
    date: '2026-05-13',
    time: '09:28',
    title: 'Menus de navegação mais modernos',
    changes: [
      'O design dos menus de navegação (separadores) nas Configurações e nos Utilizadores foi totalmente modernizado.',
      'Os separadores funcionam agora num formato "pílula" (segmented control) com melhor contraste, legibilidade e aspeto premium, tanto em modo claro como escuro.',
    ],
  },
  {
    version: '1.7.46',
    date: '2026-05-13',
    time: '09:23',
    title: 'Lista de membros de grupos mais limpa',
    changes: [
      'A gestão de grupos passou a apresentar apenas os membros atuais do grupo por defeito.',
      'Os restantes utilizadores só aparecem se utilizar a caixa de pesquisa, tornando a gestão de equipas muito mais simples sem uma lista interminável de utilizadores.',
    ],
  },
  {
    version: '1.7.45',
    date: '2026-05-13',
    time: '09:18',
    title: 'Cor da nota interna no modo escuro',
    changes: [
      'Corrigida a legibilidade do texto das notas internas quando o modo escuro está ativo, alterando a cor de fundo para uma tonalidade adequada.',
    ],
  },
  {
    version: '1.7.44',
    date: '2026-05-12',
    time: '19:43',
    title: 'Atribuição por técnicos e emails mais completos',
    changes: [
      'O campo "Atribuído a" passa a abrir imediatamente a lista de técnicos ativos disponíveis, sem obrigar a saber ou escrever o nome.',
      'Um utilizador pode manter o papel de Administrador e ser marcado também como técnico para poder receber tickets.',
      'Tickets só podem ser atribuídos a técnicos ativos ou utilizadores marcados como técnicos, evitando atribuições diretas a administradores puros.',
      'Utilizadores locais podem ser criados com emails externos ao domínio @queiroz.pt.',
      'Os emails de criação de ticket passam a incluir o conteúdo do pedido enviado pelo utilizador.',
      'SLA foi renomeado para Tempo de resposta, com 48h por defeito e ajuste para o próximo dia útil quando o prazo cai ao fim de semana.',
    ],
  },
  {
    version: '1.7.43',
    date: '2026-05-12',
    time: '18:23',
    title: 'Pesquisa móvel em conhecimento e vários técnicos por ticket',
    changes: [
      'Corrigido o campo "Em conhecimento" no detalhe do ticket em dispositivos móveis: deixa de carregar uma lista gigante e passa a mostrar apenas resultados filtrados por nome, email ou utilizador.',
      'Tickets criados por regras de encaminhamento passam a guardar também o técnico da categoria na nova lista de responsáveis.',
      'O detalhe do ticket permite agora atribuir vários técnicos ativos ao mesmo pedido, removendo ou acrescentando responsáveis sem recriar o ticket.',
      'As notificações por email passam a considerar todos os técnicos atribuídos, não apenas o primeiro responsável.',
    ],
  },
  {
    version: '1.7.42',
    date: '2026-05-11',
    time: '15:38',
    title: 'Base de conhecimento configurável e estatísticas de acesso',
    changes: [
      'Novo botão nas Configurações para ativar ou esconder a Base de conhecimento sem apagar artigos existentes.',
      'Quando a Base de conhecimento está escondida, deixa de aparecer no menu dos utilizadores e o acesso público aos artigos fica bloqueado.',
      'A página Estatísticas passa a mostrar acessos à plataforma, utilizadores ativos, evolução diária, dispositivos, browsers, utilizadores mais ativos e áreas mais usadas.',
      'O backend passa a registar acessos autenticados às APIs da plataforma para alimentar as estatísticas detalhadas.',
    ],
  },
  {
    version: '1.7.41',
    date: '2026-05-11',
    time: '14:57',
    title: 'Entra ID: todos os utilizadores exceto alunos',
    changes: [
      'A sincronização do Entra ID passa a importar todos os utilizadores ativos, incluindo contas cloud-only sem OU/onPremDN, desde que não sejam alunos.',
      'O login Microsoft deixa de bloquear utilizadores válidos por não pertencerem a uma OU previamente permitida.',
      'O diálogo de sincronização foi clarificado para indicar que os alunos continuam a ser ignorados automaticamente.',
    ],
  },
  {
    version: '1.7.40',
    date: '2026-05-11',
    time: '13:02',
    title: 'Validação clara no novo ticket',
    changes: [
      'A página de criação de tickets passa a mostrar uma caixa com os campos obrigatórios que ainda faltam preencher.',
      'Os campos em falta ficam destacados visualmente, evitando que o botão "Submeter ticket" pareça bloqueado sem explicação.',
    ],
  },
  {
    version: '1.7.39',
    date: '2026-05-11',
    time: '12:46',
    title: 'Mapeamento de Assistente Operacional',
    changes: [
      'Utilizadores sincronizados do Entra ID com departamento "ASSISTENTE OPERACIONAL" passam a receber automaticamente o papel "Não Docente".',
      'A regra aplica-se tanto no login Microsoft como na sincronização/importação de utilizadores do Entra ID.',
      'Ao arrancar, a app corrige também utilizadores já existentes com esse departamento, desde que o papel não esteja bloqueado manualmente.',
    ],
  },
  {
    version: '1.7.38',
    date: '2026-05-11',
    time: '12:00',
    title: 'Instrução de resposta nos emails',
    changes: [
      'Os emails enviados ao utilizador passam a indicar claramente que pode responder ao email para atualizar o pedido de ajuda / ticket.',
      'A indicação aparece nos emails de criação, atualização, atribuição, comentário e alteração de conteúdo do ticket.',
    ],
  },
  {
    version: '1.7.37',
    date: '2026-05-11',
    time: '10:34',
    title: 'Correção do scroll no Chrome',
    changes: [
      'O layout principal passa a ter um contentor de conteúdo dedicado ao scroll, com altura e overflow definidos de forma explícita.',
      'Corrigido um comportamento em que o Chrome podia ficar sem permitir scroll nas páginas, apesar de Safari e iPhone continuarem a funcionar.',
    ],
  },
  {
    version: '1.7.36',
    date: '2026-05-11',
    time: '10:18',
    title: 'Respostas por email via Microsoft Graph',
    changes: [
      'A importação de respostas por email passa a suportar Microsoft Graph, evitando bloqueios de IMAP/password em tenants Microsoft 365 modernos.',
      'Nova configuração MAIL_REPLY_PROVIDER=graph e GRAPH_MAIL_USER para indicar a mailbox de suporte a ler.',
      'O modo IMAP continua disponível como fallback com MAIL_REPLY_PROVIDER=imap.',
      'O botão "Ler respostas" e a sincronização automática passam a indicar nos resultados se a origem usada foi graph ou imap.',
    ],
  },
  {
    version: '1.7.29',
    date: '2026-05-10',
    time: '09:25',
    title: 'Página Sobre — autoria e método de criação',
    changes: [
      'Nova página "Sobre" no menu lateral, a seguir a "Versão / Atualizações".',
      'Descreve o autor, o método de desenvolvimento assistido por IA (Claude Code + ChatGPT/Codex) e as tecnologias utilizadas.',
    ],
  },
  {
    version: '1.7.27',
    date: '2026-05-10',
    time: '08:56',
    title: 'Safe area iOS — cabeçalho e scroll corrigidos',
    changes: [
      'Corrigido: em iPhones com notch ou Dynamic Island, o cabeçalho sobrepunha-se à barra de estado do iOS.',
      'A página de login também passa a respeitar a safe area do topo em todos os iPhones.',
    ],
  },
  {
    version: '1.7.26',
    date: '2026-05-09',
    time: '16:10',
    title: 'Navegação móvel corrigida (logo e menus sempre acessíveis)',
    changes: [
      'Corrigido: na versão móvel (browser iOS/Android e PWA), o topo da página ficava escondido atrás da barra nativa do browser.',
      'Novo layout móvel: botão de menu, logotipo e nome do agrupamento integrados no cabeçalho principal (sempre visível, nunca coberto).',
      'A barra de navegação lateral desliza a partir de baixo do cabeçalho ao tocar no ícone ≡.',
    ],
  },
  {
    version: '1.7.24',
    date: '2026-05-09',
    time: '14:05',
    title: 'App PWA para iOS e Android',
    changes: [
      'O Helpdesk Escolar é agora uma Progressive Web App (PWA) — pode ser instalada diretamente no iPhone/iPad ou Android a partir do browser, sem passar pela App Store ou Play Store.',
      'iOS: no Safari, toca em Partilhar → "Adicionar ao ecrã de início". Android/Chrome: toca nos três pontos → "Instalar app".',
      'Ícone personalizado com letra H no ecrã de início, barra de estado em azul escolar, modo standalone (sem barra do browser).',
    ],
  },
  {
    version: '1.7.23',
    date: '2026-05-09',
    time: '13:30',
    title: 'Cópia automática para OneDrive (Microsoft 365)',
    changes: [
      'Nova secção OneDrive em Backup & Restauro: ativa a cópia automática de cada backup (JSON e ZIP) para o OneDrive de um utilizador da escola.',
      'Usa as credenciais Azure AD já configuradas na app — não é necessário configurar nada separado.',
      'Requer a permissão Files.ReadWrite.All (aplicação) na app registration do Azure AD com consentimento de administrador.',
      'Pasta configurável no OneDrive; os ZIPs vão para uma subpasta full_zips/ dentro da pasta escolhida.',
      'Botão "Testar ligação" verifica as credenciais e cria um ficheiro de teste no OneDrive.',
      'Erros de upload ao OneDrive ficam visíveis no registo de cópias por entrada.',
    ],
  },
  {
    version: '1.7.22',
    date: '2026-05-09',
    time: '11:30',
    title: 'Restauro a partir de ZIP completo',
    changes: [
      'A área de importação aceita agora tanto ficheiros .json (apenas dados) como .zip (completo com anexos).',
      'Ao restaurar um ZIP completo, a base de dados é reposta a partir do tickets.db incluído no ZIP e todos os ficheiros anexados são copiados de volta.',
      'As configurações da aplicação (app_settings.json) e do backup (backup_config.json) são também restauradas do ZIP.',
      'O diálogo de confirmação indica claramente o tipo de ficheiro e o que será substituído.',
      'O resumo pós-restauro inclui o número de ficheiros de anexos recuperados.',
    ],
  },
  {
    version: '1.7.21',
    date: '2026-05-09',
    time: '07:44',
    title: 'Cópias automáticas do ZIP completo para o NAS secundário',
    changes: [
      'Nova opção "Cópias automáticas (ZIP completo)" na configuração de backup — o servidor cria automaticamente um ZIP completo (base de dados + anexos + .env) em cada intervalo configurado.',
      'O ZIP automático é guardado em subpasta "full_zips" dentro do destino principal e, se configurado, copiado para o destino secundário (outro NAS, partilha de rede, etc.).',
      'Número de ZIPs a manter configurável independentemente do número de JSONs.',
      'O registo de cópias identifica as entradas ZIP com etiqueta roxa "ZIP".',
      'Os ZIPs gerados automaticamente são excluídos do conteúdo dos novos ZIPs para evitar recursividade.',
    ],
  },
  {
    version: '1.7.20',
    date: '2026-05-08',
    time: '22:13',
    title: 'Melhorias de backup, pesquisa, SLA e de-escalação',
    changes: [
      'Pesquisa de tickets por título e descrição nas listas do utilizador e do administrador.',
      'Indicador de SLA visível nas listas de tickets — mostra tempo restante ou excedido com código de cor (verde/amarelo/laranja/vermelho).',
      'Botão "Fornecedor resolveu" no detalhe do ticket para marcar de-escalação quando o fornecedor externo resolve o problema.',
      'Botão de teste de SMTP nas configurações — envia email de teste diretamente para o administrador.',
      'Restauro de dados a partir de ficheiro JSON na página de backup — com confirmação em dois passos e resumo dos registos restaurados.',
      'Diálogo de confirmação antes de descarregar o ZIP completo, que inclui o .env com credenciais sensíveis.',
      'Correção: cópias automáticas eram registadas como "manual" em vez de "auto".',
      'Correção: agendador aguardava o intervalo completo antes da primeira cópia automática — passa a executar imediatamente ao arrancar.',
      'Correção: geração do ZIP completo deixa de carregar todos os ficheiros em memória RAM — usa ficheiro temporário em disco.',
      'Sincronização Entra ID: utilizadores removidos do Entra são agora automaticamente desativados.',
      'Hora de atualização adicionada ao rótulo de versão.',
    ],
  },
  {
    version: '1.7.19',
    date: '2026-05-08',
    time: '20:45',
    title: 'Exportação completa para recuperação catastrófica',
    changes: [
      'Novo botão "Descarregar ZIP completo": exporta tudo — base de dados SQLite, todos os ficheiros anexados, logótipo e configurações da aplicação — num único ficheiro ZIP.',
      'O ZIP inclui um ficheiro RESTAURO.txt com instruções passo a passo para repor o helpdesk numa instalação limpa.',
      'Se estiver configurado um destino secundário, é possível guardar o ZIP diretamente nesse local a partir da interface.',
      'Nota: o ficheiro .env não está incluído no ZIP porque contém segredos — deve ser guardado separadamente.',
    ],
  },
  {
    version: '1.7.18',
    date: '2026-05-08',
    time: '19:27',
    title: 'Registo persistente de backups e destino secundário',
    changes: [
      'O registo de cópias de segurança é agora persistente no servidor — as entradas mantêm-se entre sessões e recarregamentos da página.',
      'Adicionado campo "Destino secundário": após criar a cópia no local principal, o servidor copia automaticamente o ficheiro para um segundo caminho (partilha de rede, disco externo, etc.).',
      'O registo indica se a cópia foi manual ou automática, os locais onde foi guardada e eventuais erros no destino secundário.',
    ],
  },
  {
    version: '1.7.17',
    date: '2026-05-08',
    time: '08:03',
    title: 'Notificação ao fornecedor quando ticket escalado é atualizado',
    changes: [
      'Quando o assunto ou a descrição de um ticket que já foi escalado para o fornecedor são alterados pelo administrador, é enviado automaticamente um email ao fornecedor com o conteúdo atualizado.',
      'O email indica quem fez a alteração e inclui a descrição atual do pedido.',
    ],
  },
  {
    version: '1.7.16',
    date: '2026-05-08',
    time: '07:19',
    title: 'Escalação na criação e edição de conteúdo pelo administrador',
    changes: [
      'Ao criar um ticket, o administrador pode ativar "Escalar imediatamente para fornecedor" — o email de escalação é enviado ao fornecedor externo logo após a criação, sem passos extra.',
      'O administrador pode editar o assunto e a descrição de qualquer ticket através do botão Editar no topo do ticket.',
      'Quando o conteúdo é alterado, todos os participantes (autor, técnico, grupo, pessoas em conhecimento) recebem um email de notificação identificando quem fez a alteração.',
    ],
  },
  {
    version: '1.7.15',
    date: '2026-05-07',
    time: '21:08',
    title: 'Notificações automáticas para quem responde a um ticket',
    changes: [
      'Quem responde a um ticket passa a ser automaticamente adicionado às pessoas em conhecimento, ficando assim a receber todas as notificações seguintes (novas respostas, alterações de estado, fecho do ticket).',
      'Este comportamento aplica-se a qualquer utilizador que não seja já o autor, o técnico atribuído ou esteja explicitamente em conhecimento.',
    ],
  },
  {
    version: '1.7.14',
    date: '2026-05-07',
    time: '07:36',
    title: 'Aviso de modo de demonstração',
    changes: [
      'Quando o utilizador entra em modo de demonstração, aparece um aviso persistente no topo de todas as páginas a informar que os pedidos não serão processados e a indicar como entrar com a conta da escola.',
      'O aviso inclui um botão "Entrar" que redireciona diretamente para o ecrã de login.',
      'O aviso adapta-se ao modo escuro.',
    ],
  },
  {
    version: '1.7.13',
    date: '2026-05-06',
    time: '23:41',
    title: 'Pré-visualização de imagens e PDFs nos tickets',
    changes: [
      'Imagens anexadas aparecem como miniaturas diretamente no ticket — clicar abre a imagem em popup a ecrã inteiro.',
      'PDFs e outros ficheiros abrem num novo separador do browser ao clicar.',
      'As miniaturas são carregadas automaticamente quando o ticket é aberto.',
    ],
  },
  {
    version: '1.7.12',
    date: '2026-05-06',
    time: '23:19',
    title: 'Correções de upload e download de anexos',
    changes: [
      'O backend passa a aceitar qualquer formato de imagem (incluindo HEIC e WebP de dispositivos iOS/Android) além de PDF.',
      'A opção de anexar ficheiro no formulário de novo ticket passa a abrir a galeria completa do dispositivo móvel.',
      'Se um anexo falhar no upload, o ticket é criado na mesma e o utilizador é avisado do ficheiro que falhou.',
      'O download de anexos ficou mais fiável: o link temporário permanece válido durante 10 segundos para compatibilidade com todos os browsers.',
    ],
  },
  {
    version: '1.7.11',
    date: '2026-05-06',
    time: '22:54',
    title: 'Correções de anexos, mobile e branding do login',
    changes: [
      'Clicar num anexo já não devolve "Not authenticated" — o download é agora feito com o token de sessão.',
      'O botão "Submeter ticket" deixou de ficar bloqueado após escolher um ficheiro da galeria no telemóvel.',
      'A opção de receber atualizações por email fica ativa por defeito ao criar um ticket.',
      'Ficheiros da galeria iOS (HEIC e outros formatos móveis) passam a ser aceites como anexos.',
      'Página de login: título alterado para "Centro de Apoio Digital do Agrupamento".',
      'Painel lateral do login mostra agora o nome do agrupamento e o endereço www.queiroz.pt de forma destacada.',
      'Cada funcionalidade destacada no login tem agora uma cor e ícone distintos.',
      'Pesquisa de pessoas em conhecimento no detalhe do ticket passa a filtrar por endereço de email.',
    ],
  },
  {
    version: '1.7.10',
    date: '2026-05-06',
    time: '22:16',
    title: 'Diagnóstico das respostas por email',
    changes: [
      'Os emails enviados passam a definir explicitamente o Reply-To para a caixa configurada em MAIL_FROM.',
      'A sincronização IMAP passa a registar nos logs se encontrou emails não lidos, se ignorou mensagens sem marcador de ticket e se importou respostas com sucesso.',
      'Erros de ligação, autenticação ou seleção da pasta IMAP passam a ficar visíveis nos logs do backend.',
    ],
  },
  {
    version: '1.7.9',
    date: '2026-05-06',
    time: '21:43',
    title: 'Respostas por email atualizam o ticket',
    changes: [
      'Quando a caixa IMAP de respostas está configurada, respostas a emails com o assunto [Ticket #ID] passam a ser importadas automaticamente como comentários públicos no ticket.',
      'Cada resposta recebida por email atualiza a data do ticket, cria um registo no histórico e evita duplicados através do Message-ID.',
      'Os restantes participantes do ticket são notificados quando chega uma nova resposta por email.',
    ],
  },
  {
    version: '1.7.8',
    date: '2026-05-06',
    time: '21:05',
    title: 'Correção da pesquisa em conhecimento por utilizador',
    changes: [
      'No detalhe do ticket, o campo Em conhecimento passa a filtrar sugestões pelo nome, email, prefixo do email e nome de utilizador.',
      'Ao escrever diretamente um utilizador como pedropereira, o botão Adicionar passa a identificar esse utilizador quando a correspondência é exata ou única.',
    ],
  },
  {
    version: '1.7.7',
    date: '2026-05-06',
    time: '20:28',
    title: 'Pesquisa por utilizador nas pessoas em conhecimento',
    changes: [
      'A gestão de membros dos grupos internos passa a permitir pesquisar utilizadores por nome, email ou nome de utilizador.',
      'Ao criar um novo ticket, o campo Dar conhecimento a mostra também o nome de utilizador nos resultados.',
      'Na página de detalhe do ticket, a secção Em conhecimento passa a aceitar seleção por nome, email ou nome de utilizador.',
    ],
  },
  {
    version: '1.7.6',
    date: '2026-05-06',
    time: '19:52',
    title: 'Gestão de pessoas em conhecimento no ticket',
    changes: [
      'O autor do ticket e qualquer técnico ou administrador podem agora adicionar e remover pessoas em conhecimento diretamente na página de detalhe, sem ser necessário recriar o ticket.',
      'Campo de pesquisa por nome substitui a lista fixa: basta escrever parte do nome para filtrar os utilizadores disponíveis.',
      'Cada adição ou remoção fica registada no histórico do ticket com o nome da pessoa e quem fez a alteração.',
    ],
  },
  {
    version: '1.7.5',
    date: '2026-05-06',
    time: '19:14',
    title: 'Correção do modo escuro no login',
    changes: [
      'Quando o modo escuro é ativado no ecrã de login, toda a área de entrada passa a usar fundo, cartões, bordas e texto escuros coerentes.',
      'Melhorado o contraste dos textos no login escuro para evitar letras cinzentas sobre fundo claro.',
    ],
  },
  {
    version: '1.7.4',
    date: '2026-05-06',
    time: '08:49',
    title: 'Escolha de tema no login',
    changes: [
      'Página de login continua a abrir em modo claro por defeito.',
      'Adicionada opção visível Modo escuro com escolha Sim / Não no ecrã de entrada.',
      'A escolha de modo escuro no login deixa de prender o ecrã de entrada em escuro nas visitas seguintes.',
    ],
  },
  {
    version: '1.7.3',
    date: '2026-05-06',
    time: '08:31',
    title: 'Criação de tickets e login claro',
    changes: [
      'Administradores podem atribuir logo um novo ticket a pessoas em conhecimento e a equipas internas.',
      'Ao escolher equipas internas na criação do ticket, os membros passam a acompanhar o pedido e recebem notificações.',
      'A sincronização Entra passa a correr automaticamente durante a noite por defeito.',
      'A página de login abre sempre em modo claro, independentemente da preferência usada dentro da aplicação.',
      'Ecrã de entrada mais compacto, com menos espaço vazio no topo e logotipo do agrupamento maior.',
      'Botão principal de entrada renomeado para email ou conta da escola e login local escondido numa opção secundária.',
      'Referências a Active Directory removidas da área visível do login.',
    ],
  },
  {
    version: '1.7.2',
    date: '2026-05-06',
    time: '07:58',
    title: 'Categorias, técnicos ativos e tema',
    changes: [
      'Categorias padrão atualizadas para Inovar, Mail e Teams, Internet e Wi-Fi, Computadores, Impressoras, Projetores, Passwords e Outros.',
      'Cada categoria padrão recebe um ícone simples e uma cor distinta.',
      'A categoria genérica Apoio Técnico deixa de ser criada por defeito e é removida automaticamente quando não tem tickets associados.',
      'O campo Atribuído a passa a mostrar apenas técnicos ativos; administradores, direção e docentes deixam de aparecer como responsáveis diretos.',
      'Regras de encaminhamento automático só aceitam responsáveis que sejam técnicos ativos.',
      'Opção de manter o modo escuro no login tornada visível no ecrã de entrada e no topo da aplicação.',
    ],
  },
  {
    version: '1.7.1',
    date: '2026-05-06',
    time: '07:23',
    title: 'Utilizadores manuais e emails institucionais',
    changes: [
      'Adição manual de utilizadores com nome, email, papel, departamento, estado e palavra-passe definida pelo administrador.',
      'Autenticação local para utilizadores que não existam no Entra ID.',
      'Sincronização Entra passa a preferir aliases institucionais @queiroz.pt em vez de endereços @onmicrosoft.com.',
      'Botões de cancelar e guardar da sincronização Entra colocados também no topo da janela.',
      'Página de entrada com instruções de login e aviso sobre modo escuro.',
      'Ao ativar modo escuro, a aplicação pergunta se deve manter esse modo no ecrã de login.',
      'Regra de manutenção: cada atualização enviada para GitHub deve acrescentar versão e alterações nesta página.',
    ],
  },
  {
    version: '1.7.0',
    date: '2026-05-05',
    time: '22:37',
    title: 'Participantes, notificações e sincronização Entra',
    changes: [
      'Opção para dar conhecimento a pessoas ao criar um ticket.',
      'Participantes podem acompanhar, responder e anexar informação ao ticket.',
      'Opção explícita para o autor receber ou não atualizações por email.',
      'Sincronização Entra com seleção de OUs e exclusão de alunos.',
      'Campo Departamento / OU editável na gestão de utilizadores.',
      'Página de versão e histórico de atualizações.',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-05-05',
    time: '07:52',
    title: 'Escalação e gestão em lote',
    changes: [
      'Escalação de tickets para fornecedor externo configurável.',
      'Ações em lote para arquivar ou apagar tickets selecionados.',
      'Modo demo escondido até ser solicitado no ecrã de login.',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-05-04',
    time: '20:14',
    title: 'Administração escolar',
    changes: [
      'Gestão de escolas, categorias e grupos internos.',
      'Sincronização de utilizadores com Microsoft Entra ID.',
      'Permissões por papel com bloqueio manual de administradores e técnicos.',
      'Configuração de logotipo e favicon do agrupamento.',
    ],
  },
]

export function versionLabel() {
  return `v${APP_VERSION} · ${APP_VERSION_DATE} ${APP_VERSION_TIME}`
}
